const portfolio = [
    {
        "appName":  "Ultra 2",
        "packageName":  "com.amoledwatchfaces.ultra2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  true,
        "lastUpdated":  "Aug 18, 2026",
        "releaseDate":  "Aug 26, 2026",
        "icon":  "assets/icons/ultra2.webp",
        "shortDescription":  "Sleek, highly customizable watch face. Inspired by Galaxy Watch Ultra 2 Analog."
    },
    {
        "appName":  "Matte",
        "packageName":  "com.amoledwatchfaces.matte",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 7, 2026",
        "releaseDate":  "Aug 7, 2026",
        "icon":  "assets/icons/matte.webp",
        "shortDescription":  "Simple and stylish watch face with large digital clock and custom complications."
    },
    {
        "appName":  "Military 2",
        "packageName":  "com.amoledwatchfaces.military2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 17, 2026",
        "releaseDate":  "Jul 17, 2026",
        "icon":  "assets/icons/military2.webp",
        "shortDescription":  "Tactical aesthetics, an improved LCD digital font, and extensive customization."
    },
    {
        "appName":  "Vertex",
        "packageName":  "com.amoledwatchfaces.vertex",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 3, 2026",
        "releaseDate":  "Jul 3, 2026",
        "icon":  "assets/icons/vertex.webp",
        "shortDescription":  "Circular layout with 8 customizable complications. Simple, clean, and effective."
    },
    {
        "appName":  "Zenith",
        "packageName":  "com.amoledwatchfaces.zenith",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  true,
        "lastUpdated":  "Unknown",
        "releaseDate":  "Jun 10, 2026",
        "icon":  "assets/icons/zenith.webp",
        "shortDescription":  "7 custom complication slots, weather, gradient progress bars and more."
    },
    {
        "appName":  "Gravity",
        "packageName":  "com.amoledwatchfaces.gravity",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Unknown",
        "releaseDate":  "May 25, 2026",
        "icon":  "assets/icons/gravity.webp",
        "shortDescription":  "Designed with a native Wear OS aesthetic. Customizable \u0026 battery friendly."
    },
    {
        "appName":  "Epoch",
        "packageName":  "com.amoledwatchfaces.epoch",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Unknown",
        "releaseDate":  "May 11, 2026",
        "icon":  "assets/icons/epoch.webp",
        "shortDescription":  "Sleek analog watch face featuring dynamic date rings and custom complications."
    },
    {
        "appName":  "Grid",
        "packageName":  "com.amoledwatchfaces.grid",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Apr 24, 2026",
        "releaseDate":  "Apr 23, 2026",
        "icon":  "assets/icons/grid.webp",
        "shortDescription":  "Only custom complications, that\u0027s it."
    },
    {
        "appName":  "Digest",
        "packageName":  "com.amoledwatchfaces.digest",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Apr 21, 2026",
        "releaseDate":  "Apr 14, 2026",
        "icon":  "assets/icons/digest.webp",
        "shortDescription":  "Two large custom complication slots for maximum information at a glance."
    },
    {
        "appName":  "Expedition",
        "packageName":  "com.amoledwatchfaces.expedition",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Mar 30, 2026",
        "releaseDate":  "Mar 24, 2026",
        "icon":  "assets/icons/expedition.webp",
        "shortDescription":  "A highly informative watch face featuring 8 customizable complication slots."
    },
    {
        "appName":  "Utility",
        "packageName":  "com.amoledwatchfaces.utility",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Mar 16, 2026",
        "releaseDate":  "Mar 10, 2026",
        "icon":  "assets/icons/utility.webp",
        "shortDescription":  "Highly customizable material design watch face with 8 custom complications."
    },
    {
        "appName":  "Rugged 2.0",
        "packageName":  "com.amoledwatchfaces.rugged2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Mar 4, 2026",
        "releaseDate":  "Feb 23, 2026",
        "icon":  "assets/icons/rugged2.webp",
        "shortDescription":  "Built for rough conditions with rugged, bold time and custom complications."
    },
    {
        "appName":  "Weather Dashboard",
        "packageName":  "com.amoledwatchfaces.weatherDashboard",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  true,
        "lastUpdated":  "Apr 9, 2026",
        "releaseDate":  "Feb 9, 2026",
        "icon":  "assets/icons/weatherDashboard.webp",
        "shortDescription":  "Current weather, forecast, UV, rain probability and custom complications."
    },
    {
        "appName":  "Pixel Analog 2",
        "packageName":  "com.amoledwatchfaces.pixelAnalog2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Jan 21, 2026",
        "releaseDate":  "Jan 20, 2026",
        "icon":  "assets/icons/pixelAnalog2.webp",
        "shortDescription":  "Highly customizable watch face featuring a compact analog clock."
    },
    {
        "appName":  "Wayfarer",
        "packageName":  "com.amoledwatchfaces.wayfarer",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Jan 9, 2026",
        "releaseDate":  "Jan 6, 2026",
        "icon":  "assets/icons/wayfarer.webp",
        "shortDescription":  "Highly customizable, power efficient analog watch face design. Make it your own."
    },
    {
        "appName":  "Vibe",
        "packageName":  "com.amoledwatchfaces.vibe",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Nov 12, 2025",
        "releaseDate":  "Nov 12, 2025",
        "icon":  "assets/icons/vibe.webp",
        "shortDescription":  "Compact, battery friendly watch face with radial complication slots layout."
    },
    {
        "appName":  "Circle Dashboard",
        "packageName":  "com.amoledwatchfaces.circleDashboard",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  true,
        "lastUpdated":  "Apr 26, 2026",
        "releaseDate":  "Oct 13, 2025",
        "icon":  "assets/icons/circleDashboard.webp",
        "shortDescription":  "Sleek, highly customizable watch face inspired by Galaxy Watch Circle Dashboard."
    },
    {
        "appName":  "Everyday",
        "packageName":  "com.amoledwatchfaces.everyday",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Sep 29, 2025",
        "releaseDate":  "Sep 29, 2025",
        "icon":  "assets/icons/everyday.webp",
        "shortDescription":  "Simple, minimal, and highly customizable material 3 expressive watch face."
    },
    {
        "appName":  "Eccentric",
        "packageName":  "com.amoledwatchfaces.eccentric",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Sep 22, 2025",
        "releaseDate":  "Sep 22, 2025",
        "icon":  "assets/icons/eccentric.webp",
        "shortDescription":  "Modern, highly customizable watch face with distinctive digital clock fonts."
    },
    {
        "appName":  "Adaptive",
        "packageName":  "com.amoledwatchfaces.adaptive",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 10, 2025",
        "releaseDate":  "Sep 11, 2025",
        "icon":  "assets/icons/adaptive.webp",
        "shortDescription":  "Highly customizable digital watch face. Power efficient, sleek, modern design."
    },
    {
        "appName":  "Pilot",
        "packageName":  "com.amoledwatchfaces.pilot",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Aug 30, 2025",
        "releaseDate":  "Aug 23, 2025",
        "icon":  "assets/icons/pilot.webp",
        "shortDescription":  "Highly customizable hybrid watch face with dashed-arc progress bars."
    },
    {
        "appName":  "Expressive",
        "packageName":  "com.amoledwatchfaces.expressive",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 11, 2025",
        "releaseDate":  "Aug 10, 2025",
        "icon":  "assets/icons/expressive.webp",
        "shortDescription":  "Material Expressive design watch face with many configurations and theme colors."
    },
    {
        "appName":  "Aurora Analog",
        "packageName":  "com.amoledwatchfaces.auroraAnalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Feb 15, 2026",
        "releaseDate":  "Jul 24, 2025",
        "icon":  "assets/icons/auroraAnalog.webp",
        "shortDescription":  "Highly customizable analog watch face with wrist-reactive aurora lights."
    },
    {
        "appName":  "Nova",
        "packageName":  "com.amoledwatchfaces.nova",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jan 23, 2026",
        "releaseDate":  "Jul 12, 2025",
        "icon":  "assets/icons/nova.webp",
        "shortDescription":  "Futuristic, highly customizable watch face with unlimited theme combinations."
    },
    {
        "appName":  "TrackMate",
        "packageName":  "com.amoledwatchfaces.trackMate",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 1, 2025",
        "releaseDate":  "Jul 2, 2025",
        "icon":  "assets/icons/trackMate.webp",
        "shortDescription":  "Sporty, clean, and highly customizable with key data at a glance."
    },
    {
        "appName":  "Haze",
        "packageName":  "com.amoledwatchfaces.haze",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 9, 2025",
        "releaseDate":  "Jun 21, 2025",
        "icon":  "assets/icons/haze.webp",
        "shortDescription":  "Light. Minimal. Effortless. Drift through hazy summer days in style."
    },
    {
        "appName":  "Peak Shadow",
        "packageName":  "com.amoledwatchfaces.peakShadow",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  true,
        "lastUpdated":  "Jul 31, 2025",
        "releaseDate":  "Jun 8, 2025",
        "icon":  "assets/icons/peakShadow.webp",
        "shortDescription":  "Inspired by Nature. A unique, colorful, and customizable watch face."
    },
    {
        "appName":  "Apex 2.0",
        "packageName":  "com.amoledwatchfaces.apex2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  true,
        "lastUpdated":  "Feb 27, 2026",
        "releaseDate":  "May 29, 2025",
        "icon":  "assets/icons/apex2.webp",
        "shortDescription":  "2nd version of the Apex design. Enhanced with hourly-daily weather forecast."
    },
    {
        "appName":  "TACT 5",
        "packageName":  "com.amoledwatchfaces.tact5",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Nov 28, 2025",
        "releaseDate":  "May 21, 2025",
        "icon":  "assets/icons/tact5.webp",
        "shortDescription":  "Modern, tactical watch face with 8 custom complication slots and unique themes."
    },
    {
        "appName":  "Explorer",
        "packageName":  "com.amoledwatchfaces.explorer",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Feb 26, 2026",
        "releaseDate":  "May 13, 2025",
        "icon":  "assets/icons/explorer.webp",
        "shortDescription":  "Classy analog watch face with 8 custom complication slots and many color themes."
    },
    {
        "appName":  "Boost",
        "packageName":  "com.amoledwatchfaces.boost",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 31, 2025",
        "releaseDate":  "Apr 29, 2025",
        "icon":  "assets/icons/boost.webp",
        "shortDescription":  "Highly customizable, fitness oriented watch face with beautiful color bars."
    },
    {
        "appName":  "Stealth",
        "packageName":  "com.amoledwatchfaces.stealth",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 31, 2025",
        "releaseDate":  "Apr 22, 2025",
        "icon":  "assets/icons/stealth.webp",
        "shortDescription":  "Highly customizable watch face. Themes, complications, clock fonts and more."
    },
    {
        "appName":  "Military",
        "packageName":  "com.amoledwatchfaces.military",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Oct 16, 2025",
        "releaseDate":  "Apr 9, 2025",
        "icon":  "assets/icons/military.webp",
        "shortDescription":  "Own-designed LCD digital clock font plus many color and style customizations."
    },
    {
        "appName":  "Roto",
        "packageName":  "com.amoledwatchfaces.roto",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 30, 2025",
        "releaseDate":  "Apr 2, 2025",
        "icon":  "assets/icons/roto.webp",
        "shortDescription":  "A unique and customizable watch face which rotates its layout every minute."
    },
    {
        "appName":  "Outdoor",
        "packageName":  "com.amoledwatchfaces.outdoor",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jun 5, 2026",
        "releaseDate":  "Mar 19, 2025",
        "icon":  "assets/icons/outdoor.webp",
        "shortDescription":  "Highly customizable, colorful, \u0026 informative watch face for outdoor adventures."
    },
    {
        "appName":  "Glide",
        "packageName":  "com.amoledwatchfaces.glide",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 30, 2025",
        "releaseDate":  "Mar 13, 2025",
        "icon":  "assets/icons/glide.webp",
        "shortDescription":  "Big \u0026 bold digital clock, custom complications, active and modern design."
    },
    {
        "appName":  "Compact",
        "packageName":  "com.amoledwatchfaces.compact",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 30, 2025",
        "releaseDate":  "Mar 4, 2025",
        "icon":  "assets/icons/compact.webp",
        "shortDescription":  "Sleek, modern watch face with 8 custom complications, optional fonts and themes."
    },
    {
        "appName":  "Soft",
        "packageName":  "com.amoledwatchfaces.soft",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 29, 2025",
        "releaseDate":  "Feb 24, 2025",
        "icon":  "assets/icons/soft.webp",
        "shortDescription":  "Highly readable, minimal watch face with a few custom complication slots."
    },
    {
        "appName":  "Ultra Analog",
        "packageName":  "com.amoledwatchfaces.ultra",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "May 18, 2026",
        "releaseDate":  "Feb 17, 2025",
        "icon":  "assets/icons/ultra.webp",
        "shortDescription":  "Modern \u0026 highly customizable watch face, inspired by Galaxy Watch Ultra Analog."
    },
    {
        "appName":  "Maverick",
        "packageName":  "com.amoledwatchfaces.maverick",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jun 1, 2026",
        "releaseDate":  "Feb 5, 2025",
        "icon":  "assets/icons/maverick.webp",
        "shortDescription":  "Time redefined. Maverick is your customizable watch face for everyday adventure."
    },
    {
        "appName":  "Radial",
        "packageName":  "com.amoledwatchfaces.radial",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Jan 27, 2025",
        "icon":  "assets/icons/radial.webp",
        "shortDescription":  "Digital clock with optional fonts, encircled by 8 custom complications."
    },
    {
        "appName":  "Kinetic",
        "packageName":  "com.amoledwatchfaces.kinetic",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Feb 26, 2026",
        "releaseDate":  "Jan 9, 2025",
        "icon":  "assets/icons/kinetic.webp",
        "shortDescription":  "Stylish, dynamic watch face with themes, custom complications, and dark mode."
    },
    {
        "appName":  "Aurora",
        "packageName":  "com.amoledwatchfaces.aurora",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 30, 2025",
        "releaseDate":  "Dec 30, 2024",
        "icon":  "assets/icons/aurora.webp",
        "shortDescription":  "A minimal and customizable watch face with wrist-reactive aurora lights."
    },
    {
        "appName":  "Weather Analog",
        "packageName":  "com.amoledwatchfaces.weatherAnalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  true,
        "lastUpdated":  "Jul 31, 2025",
        "releaseDate":  "Dec 16, 2024",
        "icon":  "assets/icons/weatherAnalog.webp",
        "shortDescription":  "Track current weather and 10-hour forecasts in a minimal analog design."
    },
    {
        "appName":  "Weather Forecast",
        "packageName":  "com.amoledwatchfaces.forecast",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  true,
        "lastUpdated":  "Jan 14, 2026",
        "releaseDate":  "Dec 3, 2024",
        "icon":  "assets/icons/forecast.webp",
        "shortDescription":  "Hourly and daily weather forecast, current condition, temperature, UV and more!"
    },
    {
        "appName":  "Summit",
        "packageName":  "com.amoledwatchfaces.summit",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Nov 23, 2024",
        "icon":  "assets/icons/summit.webp",
        "shortDescription":  "Custom complications, sleek design, time modes and endless style options."
    },
    {
        "appName":  "Pioneer",
        "packageName":  "com.amoledwatchfaces.pioneer",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 29, 2025",
        "releaseDate":  "Nov 8, 2024",
        "icon":  "assets/icons/pioneer.webp",
        "shortDescription":  "Packed with material themes, clock fonts \u0026 8 complication slots for flexibility!"
    },
    {
        "appName":  "Pathfinder",
        "packageName":  "com.amoledwatchfaces.pathfinder",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Oct 27, 2024",
        "icon":  "assets/icons/pathfinder.webp",
        "shortDescription":  "Analog watch face with customizable themes, watch hands, and complications."
    },
    {
        "appName":  "Halo",
        "packageName":  "com.amoledwatchfaces.halo",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jan 23, 2026",
        "releaseDate":  "Oct 10, 2024",
        "icon":  "assets/icons/halo.webp",
        "shortDescription":  "Sleek, modern, and feature packed watch face. Mix colors, fonts \u0026 complications!"
    },
    {
        "appName":  "Spooky",
        "packageName":  "com.amoledwatchfaces.spooky",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Sep 24, 2025",
        "releaseDate":  "Sep 29, 2024",
        "icon":  "assets/icons/spooky.webp",
        "shortDescription":  "Boo! Meet Spooky, a Halloween watch face with a lot of features. Happy haunting!"
    },
    {
        "appName":  "InfoHub",
        "packageName":  "com.amoledwatchfaces.infoHub",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Sep 15, 2024",
        "icon":  "assets/icons/infoHub.webp",
        "shortDescription":  "Your personal information hub with 6 customizable complications \u0026 many themes."
    },
    {
        "appName":  "Text Time",
        "packageName":  "com.amoledwatchfaces.textTime",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 29, 2025",
        "releaseDate":  "Sep 2, 2024",
        "icon":  "assets/icons/textTime.webp",
        "shortDescription":  "Colorful, customizable, \u0026 multilanguage watch face with text-based time display."
    },
    {
        "appName":  "Adventurer",
        "packageName":  "com.amoledwatchfaces.adventurer",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 28, 2025",
        "releaseDate":  "Aug 20, 2024",
        "icon":  "assets/icons/adventurer.webp",
        "shortDescription":  "Complex \u0026 highly customizable watch face. Inspired by Active from Pixel Watch 3."
    },
    {
        "appName":  "Breezy",
        "packageName":  "com.amoledwatchfaces.breezy",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 29, 2025",
        "releaseDate":  "Aug 11, 2024",
        "icon":  "assets/icons/breezy.webp",
        "shortDescription":  "Simple, stylish \u0026 fresh watch face. Customize colors, gradients \u0026 complications."
    },
    {
        "appName":  "Symmetrical",
        "packageName":  "com.amoledwatchfaces.symmetrical",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 1, 2025",
        "releaseDate":  "Aug 4, 2024",
        "icon":  "assets/icons/symmetrical.webp",
        "shortDescription":  "Mix and match complication slots, fonts, and themes to create a unique look."
    },
    {
        "appName":  "Just Weather",
        "packageName":  "com.amoledwatchfaces.weather",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  true,
        "lastUpdated":  "Dec 1, 2024",
        "releaseDate":  "Jul 27, 2024",
        "icon":  "assets/icons/weather.webp",
        "shortDescription":  "Current weather, conditions, forecast, chance of rain, UV \u0026 two complications."
    },
    {
        "appName":  "Main Goals",
        "packageName":  "com.amoledwatchfaces.mainGoals",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Jul 23, 2024",
        "icon":  "assets/icons/mainGoals.webp",
        "shortDescription":  "Goal-focused design. Optional fonts, material themes, \u0026 custom complications."
    },
    {
        "appName":  "Analog M4",
        "packageName":  "com.amoledwatchfaces.analogm4",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Aug 6, 2024",
        "releaseDate":  "Jul 16, 2024",
        "icon":  "assets/icons/analogm4.webp",
        "shortDescription":  "Customizable Material You watch face. 8 complications, watch hand styles \u0026 more!"
    },
    {
        "appName":  "Binary 2.0",
        "packageName":  "com.amoledwatchfaces.binary2",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Oct 13, 2025",
        "releaseDate":  "Jul 2, 2024",
        "icon":  "assets/icons/binary2.webp",
        "shortDescription":  "Binary-coded sexagesimal watch face design. Tap to reveal digital clock!"
    },
    {
        "appName":  "Apex SE",
        "packageName":  "com.amoledwatchfaces.apex",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Feb 23, 2026",
        "releaseDate":  "Jun 21, 2024",
        "icon":  "assets/icons/apex.webp",
        "shortDescription":  "Highly customizable watch face. Optional fonts, gradients, custom complications."
    },
    {
        "appName":  "Inverted",
        "packageName":  "com.amoledwatchfaces.inverted",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 3, 2025",
        "releaseDate":  "May 30, 2024",
        "icon":  "assets/icons/inverted.webp",
        "shortDescription":  "Watch time come alive as digital clock fills with each passing second."
    },
    {
        "appName":  "Classic M5",
        "packageName":  "com.amoledwatchfaces.classicm5",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Jul 17, 2025",
        "releaseDate":  "May 19, 2024",
        "icon":  "assets/icons/classicm5.webp",
        "shortDescription":  "Don\u0027t settle, create your perfect classic watch face. Use 60+ colors \u0026 themes."
    },
    {
        "appName":  "Streamlined",
        "packageName":  "com.amoledwatchfaces.streamlined",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 8, 2025",
        "releaseDate":  "May 8, 2024",
        "icon":  "assets/icons/streamlined.webp",
        "shortDescription":  "Animated digital clock movement. 6 custom complications \u0026 two time modes."
    },
    {
        "appName":  "Perpetual",
        "packageName":  "com.amoledwatchfaces.perpetual",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 28, 2025",
        "releaseDate":  "May 3, 2024",
        "icon":  "assets/icons/perpetual.webp",
        "shortDescription":  "Battery friendly digital design. Customizable \u0026 powered by Watch Face Format."
    },
    {
        "appName":  "Outlined",
        "packageName":  "com.amoledwatchfaces.outlined",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Apr 8, 2026",
        "releaseDate":  "Apr 22, 2024",
        "icon":  "assets/icons/outlined.webp",
        "shortDescription":  "Customizable Outlined Fonts. Watch Face Format. Battery friendly Digital Clock."
    },
    {
        "appName":  "Classic M3",
        "packageName":  "com.amoledwatchfaces.classicm3",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Aug 21, 2025",
        "releaseDate":  "Apr 9, 2024",
        "icon":  "assets/icons/classicm3.webp",
        "shortDescription":  "Inspired by Pixel Watch \"Classic\" watch face. Optimized \u0026 fully customizable."
    },
    {
        "appName":  "Nomad",
        "packageName":  "com.amoledwatchfaces.nomad",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 30, 2025",
        "releaseDate":  "Apr 4, 2024",
        "icon":  "assets/icons/nomad.webp",
        "shortDescription":  "Be a Digital Nomad with this visually appealing \u0026 customizable watch face."
    },
    {
        "appName":  "TimeMode",
        "packageName":  "com.amoledwatchfaces.timeMode",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jun 2, 2025",
        "releaseDate":  "Mar 26, 2024",
        "icon":  "assets/icons/timemode.webp",
        "shortDescription":  "4 Time Modes. 8 custom complications. Battery friendly \u0026 customizable."
    },
    {
        "appName":  "TimeFlow",
        "packageName":  "com.amoledwatchfaces.timeFlow",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 28, 2025",
        "releaseDate":  "Mar 18, 2024",
        "icon":  "assets/icons/timeflow.webp",
        "shortDescription":  "Unique watch face design. Watch Face Format. Battery friendly. True Black BG."
    },
    {
        "appName":  "Arcs D5",
        "packageName":  "com.amoledwatchfaces.arcsd5",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 23, 2025",
        "releaseDate":  "Mar 12, 2024",
        "icon":  "assets/icons/arcsd5.webp",
        "shortDescription":  "Arcs digital version with customizable time fonts and 8 custom complications."
    },
    {
        "appName":  "Basic Analog",
        "packageName":  "com.amoledwatchfaces.basicAnalog",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Apr 8, 2025",
        "releaseDate":  "Mar 7, 2024",
        "icon":  "assets/icons/basicanalog.webp",
        "shortDescription":  "Simple analog watch face inspired by Watch Face Format loading screen."
    },
    {
        "appName":  "Arcs N6",
        "packageName":  "com.amoledwatchfaces.arcsn6",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "May 14, 2025",
        "releaseDate":  "Feb 29, 2024",
        "icon":  "assets/icons/arcsn6.webp",
        "shortDescription":  "Analog Watch Face Format watch face. Clean \u0026 Customizable design. Gradient Arcs."
    },
    {
        "appName":  "Widgets 2",
        "packageName":  "com.amoledwatchfaces.widgets2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Feb 26, 2024",
        "icon":  "assets/icons/widgets2.webp",
        "shortDescription":  "8 custom complications. Custom Time Fonts. Beautiful color schemes. A++ Design."
    },
    {
        "appName":  "Horizon 9",
        "packageName":  "com.amoledwatchfaces.horizon9",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 22, 2024",
        "releaseDate":  "Feb 12, 2024",
        "icon":  "assets/icons/horizon9.webp",
        "shortDescription":  "Digital OLED watch face. 7 segment font. 6 custom complications. Optimized."
    },
    {
        "appName":  "Nord SE",
        "packageName":  "com.amoledwatchfaces.nord",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jun 10, 2026",
        "releaseDate":  "Feb 5, 2024",
        "icon":  "assets/icons/nord.webp",
        "shortDescription":  "Watch Face Format 2. Unlimited customizations. 8 Custom complications."
    },
    {
        "appName":  "Gamer V1",
        "packageName":  "com.amoledwatchfaces.gamerv1",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Sep 1, 2024",
        "releaseDate":  "Jan 21, 2024",
        "icon":  "assets/icons/gamerv1.webp",
        "shortDescription":  "For gaming enthusiasts. Hi-res, gaming font, game creatures and unique look."
    },
    {
        "appName":  "Manager",
        "packageName":  "com.amoledwatchfaces.manager",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Jan 15, 2024",
        "icon":  "assets/icons/manager.webp",
        "shortDescription":  "Boost productivity with this sleek, battery-friendly \u0026 customizable watch face."
    },
    {
        "appName":  "Active 2",
        "packageName":  "com.amoledwatchfaces.active2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Sep 12, 2025",
        "releaseDate":  "Jan 4, 2024",
        "icon":  "assets/icons/active2.webp",
        "shortDescription":  "Fitness oriented design. Custom complications. Battery friendly. True Black BG."
    },
    {
        "appName":  "Dual Tone",
        "packageName":  "com.amoledwatchfaces.dualtone",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jul 29, 2025",
        "releaseDate":  "Dec 19, 2023",
        "icon":  "assets/icons/dualtone.webp",
        "shortDescription":  "Unique dual tone color themes and digital clock glow effect. Make it your own!"
    },
    {
        "appName":  "InfoGraph 2",
        "packageName":  "com.amoledwatchfaces.infograph2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Sep 13, 2025",
        "releaseDate":  "Dec 6, 2023",
        "icon":  "assets/icons/infograph2.webp",
        "shortDescription":  "Highly customizable digital watch face for all Wear OS 4+ smartwatches."
    },
    {
        "appName":  "InfoBlock 2",
        "packageName":  "com.amoledwatchfaces.infoblock2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Aug 2, 2025",
        "releaseDate":  "Nov 30, 2023",
        "icon":  "assets/icons/infoblock2.webp",
        "shortDescription":  "Gradient progress bars. 8 custom complications. Battery friendly. InfoBlock v2"
    },
    {
        "appName":  "Analog M3",
        "packageName":  "com.amoledwatchfaces.analogm3",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Jul 29, 2025",
        "releaseDate":  "Nov 16, 2023",
        "icon":  "assets/icons/analogm3.webp",
        "shortDescription":  "Unique material 3 design analog watch face. Customizable themes and watch hands."
    },
    {
        "appName":  "Glance X",
        "packageName":  "com.amoledwatchfaces.glancex",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Nov 7, 2023",
        "icon":  "assets/icons/glancex.webp",
        "shortDescription":  "See everything at a GLANCE. Perfect look on Pixel Watch \u0026 lot of information."
    },
    {
        "appName":  "Lucid",
        "packageName":  "com.amoledwatchfaces.lucid",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Oct 23, 2023",
        "icon":  "assets/icons/lucid.webp",
        "shortDescription":  "Highly readable design. Material design. Watch Face Format. Battery friendly."
    },
    {
        "appName":  "Chrono",
        "packageName":  "com.amoledwatchfaces.chrono",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Oct 11, 2023",
        "icon":  "assets/icons/chrono.webp",
        "shortDescription":  "7 custom complications. Battery Friendly. Hybrid design. Multiple themes."
    },
    {
        "appName":  "React 2",
        "packageName":  "com.amoledwatchfaces.react2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Oct 3, 2023",
        "icon":  "assets/icons/react2.webp",
        "shortDescription":  "2nd edition of our React design. Modern, battery friendly and customizable!"
    },
    {
        "appName":  "Modular",
        "packageName":  "com.amoledwatchfaces.modular",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 15, 2024",
        "releaseDate":  "Sep 24, 2023",
        "icon":  "assets/icons/modular.webp",
        "shortDescription":  "Modular design. Optional time font settings. Battery friendly \u0026 pixel perfect."
    },
    {
        "appName":  "Sprint",
        "packageName":  "com.amoledwatchfaces.sprint",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Sep 11, 2023",
        "icon":  "assets/icons/sprint.webp",
        "shortDescription":  "Sporty watch face made in Watch Face Format. Battery friendly and customizable."
    },
    {
        "appName":  "Huge Time",
        "packageName":  "com.amoledwatchfaces.hugetime",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Aug 22, 2023",
        "icon":  "assets/icons/hugetime.webp",
        "shortDescription":  "Battery friendly watch face with 6 custom complications and huge digital clock."
    },
    {
        "appName":  "Control Dash",
        "packageName":  "com.amoledwatchfaces.controldash",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 16, 2023",
        "icon":  "assets/icons/controldash.webp",
        "shortDescription":  "Productivity watch face with 6 custom complications \u0026 pure black background."
    },
    {
        "appName":  "Angular",
        "packageName":  "com.amoledwatchfaces.angular",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 11, 2023",
        "icon":  "assets/icons/angular.webp",
        "shortDescription":  "Sharp edges, 7x custom complication, true black background \u0026 battery friendly."
    },
    {
        "appName":  "Pulse 2",
        "packageName":  "com.amoledwatchfaces.pulse2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 2, 2023",
        "icon":  "assets/icons/pulse2.webp",
        "shortDescription":  "Health \u0026 Fitness oriented digital watch face. Four Complication slots \u0026 Black BG"
    },
    {
        "appName":  "Rugged",
        "packageName":  "com.amoledwatchfaces.rugged",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jul 29, 2023",
        "icon":  "assets/icons/rugged.webp",
        "shortDescription":  "Rugged \u0026 rough, BIG digital watch face with many custom complications slots."
    },
    {
        "appName":  "Pride",
        "packageName":  "com.amoledwatchfaces.pride",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jul 2, 2023",
        "icon":  "assets/icons/pride.webp",
        "shortDescription":  "Pride Month watch face. With LGBTQ+ Rainbow Flags and Symbols. Battery friendly."
    },
    {
        "appName":  "TACT THREE",
        "packageName":  "com.amoledwatchfaces.tactthree",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jun 18, 2023",
        "icon":  "assets/icons/tactthree.webp",
        "shortDescription":  "Tactical watch face for Wear OS 4 \u0026 3(API 30+). Battery friendly \u0026 customizable."
    },
    {
        "appName":  "Material You 2",
        "packageName":  "com.amoledwatchfaces.materialyou2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jun 5, 2023",
        "icon":  "assets/icons/materialyou2.webp",
        "shortDescription":  "2nd edition of Material You watch face. /W two progress bars \u0026 mesh backgrounds."
    },
    {
        "appName":  "Material 4",
        "packageName":  "com.amoledwatchfaces.material4",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 31, 2023",
        "icon":  "assets/icons/material4.webp",
        "shortDescription":  "Digital watch face design. Modern looking, hi-res \u0026 battery friendly."
    },
    {
        "appName":  "Pacific E",
        "packageName":  "com.amoledwatchfaces.pacifice",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 25, 2023",
        "icon":  "assets/icons/pacifice.webp",
        "shortDescription":  "Enhanced version of Pixel Pacific face. Works on any Wear OS API 28+ device."
    },
    {
        "appName":  "Engine",
        "packageName":  "com.amoledwatchfaces.engine",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "May 17, 2026",
        "releaseDate":  "May 19, 2023",
        "icon":  "assets/icons/engine.webp",
        "shortDescription":  "Premium digital watch face. Customizable. Unique \u0026 hi-res design."
    },
    {
        "appName":  "Concentric 1",
        "packageName":  "com.amoledwatchfaces.concentric1",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 16, 2023",
        "icon":  "assets/icons/concentric1.webp",
        "shortDescription":  "Clean digital watch face. Battery \u0026 OLED friendly. True Black BG \u0026 customizable."
    },
    {
        "appName":  "NANO x1",
        "packageName":  "com.amoledwatchfaces.nanox1",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 5, 2023",
        "icon":  "assets/icons/nanox1.webp",
        "shortDescription":  "Analog \u0026 Digital Wear OS design. Battery friendly, customizable \u0026 colorful."
    },
    {
        "appName":  "Digital Informer",
        "packageName":  "com.amoledwatchfaces.digitalinformer",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Mar 31, 2026",
        "releaseDate":  "May 1, 2023",
        "icon":  "assets/icons/digitalinformer.webp",
        "shortDescription":  "Material design watch face for Wear OS devices. Battery friendly \u0026 customizable."
    },
    {
        "appName":  "Tempo",
        "packageName":  "com.amoledwatchfaces.tempo",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 24, 2023",
        "icon":  "assets/icons/tempo.webp",
        "shortDescription":  "Sporty watch face with custom complications \u0026 unlimited color styles"
    },
    {
        "appName":  "Alpine",
        "packageName":  "com.amoledwatchfaces.alpine",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 18, 2023",
        "icon":  "assets/icons/alpine.webp",
        "shortDescription":  "Hybrid watch face with large digital clock and 8 custom complication slots."
    },
    {
        "appName":  "Photo",
        "packageName":  "com.amoledwatchfaces.photowatchface",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 12, 2023",
        "icon":  "assets/icons/photowatchface.webp",
        "shortDescription":  "Photo Image watch face! Choose one of 10 photos or use a photo complication."
    },
    {
        "appName":  "Nitrous",
        "packageName":  "com.amoledwatchfaces.nitrous",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 8, 2023",
        "icon":  "assets/icons/nitrous.webp",
        "shortDescription":  "Customizable Analog design. Many custom complications. Battery friendly."
    },
    {
        "appName":  "React",
        "packageName":  "com.amoledwatchfaces.react",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Mar 30, 2023",
        "icon":  "assets/icons/react.webp",
        "shortDescription":  "Battery friendly Wear OS watch face. Many color styles \u0026 custom complications."
    },
    {
        "appName":  "Guard",
        "packageName":  "com.amoledwatchfaces.guard",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Mar 21, 2023",
        "icon":  "assets/icons/guard.webp",
        "shortDescription":  "Digital watch face for Wear OS. Customizable. Battery Friendly. Pixel Perfect."
    },
    {
        "appName":  "Marine Digital",
        "packageName":  "com.amoledwatchfaces.marine",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 28, 2023",
        "icon":  "assets/icons/marine.webp",
        "shortDescription":  "High quality Wear OS Watch face. Pixel perfect design \u0026 battery friendly."
    },
    {
        "appName":  "MNML Analog",
        "packageName":  "com.amoledwatchfaces.mnmlanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 23, 2023",
        "icon":  "assets/icons/mnmlanalog.webp",
        "shortDescription":  "Truly minimal Wear OS watch face. Battery friendly and customizable."
    },
    {
        "appName":  "Heart Rate",
        "packageName":  "com.amoledwatchfaces.xface",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 13, 2023",
        "icon":  "assets/icons/xface.webp",
        "shortDescription":  "Track your heart rate in real time."
    },
    {
        "appName":  "TACT TWO",
        "packageName":  "com.amoledwatchfaces.tacttwo",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 6, 2023",
        "icon":  "assets/icons/tacttwo.webp",
        "shortDescription":  "Tactical Wear OS Watch face. Customizable \u0026 low power consumption. Pixel perfect"
    },
    {
        "appName":  "InfoBlock",
        "packageName":  "com.amoledwatchfaces.infoblock",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 1, 2023",
        "icon":  "assets/icons/infoblock.webp",
        "shortDescription":  "Info Brick inspired watch face. Battery friendly \u0026 Customizable."
    },
    {
        "appName":  "Circuit",
        "packageName":  "com.amoledwatchfaces.circuit",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jan 23, 2023",
        "icon":  "assets/icons/circuit.webp",
        "shortDescription":  "True black background watch face. 7x custom complications \u0026 30 color themes"
    },
    {
        "appName":  "Progress",
        "packageName":  "com.amoledwatchfaces.progress",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jan 13, 2023",
        "icon":  "assets/icons/progress.webp",
        "shortDescription":  "A unique Wear OS watch face with time represented by progress bars."
    },
    {
        "appName":  "Analog PRO",
        "packageName":  "com.amoledwatchfaces.analogpro",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "May 17, 2026",
        "releaseDate":  "Jan 3, 2023",
        "icon":  "assets/icons/analogpro.webp",
        "shortDescription":  "Premium Wear OS watch face. Analog \u0026 modern design. Fully customizable."
    },
    {
        "appName":  "Athlete 2 Lite",
        "packageName":  "com.amoledwatchfaces.athlete2lite",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 17, 2022",
        "icon":  "assets/icons/athlete2lite.webp",
        "shortDescription":  "Lite version of our Athlete 2 watch face. Gradient bars \u0026 custom complications."
    },
    {
        "appName":  "Athlete 2",
        "packageName":  "com.amoledwatchfaces.athlete2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 13, 2022",
        "icon":  "assets/icons/athlete2.webp",
        "shortDescription":  "Health \u0026 Fitness oriented Watch face for Wear OS 3+. Optimized \u0026 customizable."
    },
    {
        "appName":  "Pulse",
        "packageName":  "com.amoledwatchfaces.pulse",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 2, 2022",
        "icon":  "assets/icons/pulse.webp",
        "shortDescription":  "Many custom complications. Gradient bars. True blacks = Battery friendly."
    },
    {
        "appName":  "Pixel OLED",
        "packageName":  "com.amoledwatchfaces.pixeloled",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 25, 2022",
        "icon":  "assets/icons/pixeloled.webp",
        "shortDescription":  "Material You (Pixel style) Watch face for Wear OS with custom complications"
    },
    {
        "appName":  "HYB",
        "packageName":  "com.amoledwatchfaces.hyb",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 18, 2022",
        "icon":  "assets/icons/hyb.webp",
        "shortDescription":  "Big gradient digital hours. Progress bar minutes \u0026 seconds. Premium feel."
    },
    {
        "appName":  "Analog xT",
        "packageName":  "com.amoledwatchfaces.analogxt",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 15, 2022",
        "icon":  "assets/icons/analogxt.webp",
        "shortDescription":  "Simple, analog Wear OS watch face."
    },
    {
        "appName":  "Fit X",
        "packageName":  "com.amoledwatchfaces.fitx",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 8, 2022",
        "icon":  "assets/icons/fitx.webp",
        "shortDescription":  "Health \u0026 Fitness related Watch face. Customizable # Battery friendly."
    },
    {
        "appName":  "Slim Digital",
        "packageName":  "com.amoledwatchfaces.slimdigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 6, 2022",
        "icon":  "assets/icons/slimdigital.webp",
        "shortDescription":  "Wear OS watch face. Clean \u0026 Big digital time. Complications. True black BG."
    },
    {
        "appName":  "Simple Analog",
        "packageName":  "com.amoledwatchfaces.simpleanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 25, 2022",
        "icon":  "assets/icons/simpleanalog.webp",
        "shortDescription":  "Simple analog Wear OS watch face. Material style. True black BG. Customizable."
    },
    {
        "appName":  "Widgets",
        "packageName":  "com.amoledwatchfaces.widgets1",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Feb 17, 2026",
        "releaseDate":  "Oct 16, 2022",
        "icon":  "assets/icons/widgets1.webp",
        "shortDescription":  "8x custom complication. Battery friendly and customizable Wear OS watch face."
    },
    {
        "appName":  "Big Digital",
        "packageName":  "com.amoledwatchfaces.bigdigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 14, 2022",
        "icon":  "assets/icons/bigdigital.webp",
        "shortDescription":  "Wear OS watch face with big digital time. Battery friendly. Small app size."
    },
    {
        "appName":  "Weather Digital",
        "packageName":  "com.amoledwatchfaces.weatherdigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Feb 15, 2026",
        "releaseDate":  "Sep 30, 2022",
        "icon":  "assets/icons/weatherdigital.webp",
        "shortDescription":  "Wear OS watch face with a large weather complication and big digital clock."
    },
    {
        "appName":  "Material You",
        "packageName":  "com.amoledwatchfaces.materialyou",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 26, 2022",
        "icon":  "assets/icons/materialyou.webp",
        "shortDescription":  "Created for Wear OS. Material You design. Battery Friendly. Customizable."
    },
    {
        "appName":  "Health 2",
        "packageName":  "com.amoledwatchfaces.healthface2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 28, 2022",
        "icon":  "assets/icons/healthface2.webp",
        "shortDescription":  "Fitness oriented watch face for wearable devices with Wear OS. Battery friendly."
    },
    {
        "appName":  "xViper",
        "packageName":  "com.amoledwatchfaces.xviper",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 21, 2022",
        "icon":  "assets/icons/xviper.webp",
        "shortDescription":  "Modern \u0026 unique analog Wear OS watch face. Battery friendly \u0026 customizable."
    },
    {
        "appName":  "Pace 3",
        "packageName":  "com.amoledwatchfaces.pace3",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 15, 2022",
        "icon":  "assets/icons/pace3.webp",
        "shortDescription":  "Fitness Watch face with two RANGED_VALUE custom complications. Battery friendly."
    },
    {
        "appName":  "Gradient",
        "packageName":  "com.amoledwatchfaces.gradient",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 10, 2022",
        "icon":  "assets/icons/gradient.webp",
        "shortDescription":  "Gradient animated Wear OS watch face with big digital font \u0026 true black BG"
    },
    {
        "appName":  "Material 3",
        "packageName":  "com.amoledwatchfaces.material3",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 3, 2022",
        "icon":  "assets/icons/material3.webp",
        "shortDescription":  "Material 3 design (Material You) Watch face for Wear OS /w custom complications"
    },
    {
        "appName":  "TACT Q",
        "packageName":  "com.amoledwatchfaces.tactq",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jul 28, 2022",
        "icon":  "assets/icons/tactq.webp",
        "shortDescription":  "Customizable Wear OS Watch face with tactical look \u0026 camouflage backgrounds"
    },
    {
        "appName":  "Retro Digital",
        "packageName":  "com.amoledwatchfaces.retro",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jul 14, 2022",
        "icon":  "assets/icons/retro.webp",
        "shortDescription":  "\"Casio\" style Wear OS retro digital battery friendly and customizable watch face"
    },
    {
        "appName":  "Edge",
        "packageName":  "com.amoledwatchfaces.edge",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jul 6, 2022",
        "icon":  "assets/icons/edge.webp",
        "shortDescription":  "Simple Wear OS watch face with custom complications. Battery and OLED friendly."
    },
    {
        "appName":  "Sportive",
        "packageName":  "com.amoledwatchfaces.sportive",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jun 29, 2022",
        "icon":  "assets/icons/sportive.webp",
        "shortDescription":  "Premium Wear OS watch face. Customizable, hi-res and battery friendly."
    },
    {
        "appName":  "Simple Digital",
        "packageName":  "com.amoledwatchfaces.simpledigital",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Apr 30, 2026",
        "releaseDate":  "Jun 26, 2022",
        "icon":  "assets/icons/simpledigital.webp",
        "shortDescription":  "Battery friendly, digital Wear OS watch face with custom complications."
    },
    {
        "appName":  "Catalyst",
        "packageName":  "com.amoledwatchfaces.catalyst",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jun 21, 2022",
        "icon":  "assets/icons/catalyst.webp",
        "shortDescription":  "Ported from Tizen OS. Premium design. Many customization options. High res"
    },
    {
        "appName":  "Athlete 1",
        "packageName":  "com.amoledwatchfaces.athlete1",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jun 14, 2022",
        "icon":  "assets/icons/athlete1.webp",
        "shortDescription":  "Health oriented Wear OS watch face for athletes and fitness enthusiasts."
    },
    {
        "appName":  "TACT ONE",
        "packageName":  "com.amoledwatchfaces.tactone",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 17, 2025",
        "releaseDate":  "Jun 4, 2022",
        "icon":  "assets/icons/tactone.webp",
        "shortDescription":  "Tactical Wear OS watch face. Digital time. Background Dimmer. True black BG."
    },
    {
        "appName":  "Sport B",
        "packageName":  "com.amoledwatchfaces.sportb",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 26, 2022",
        "icon":  "assets/icons/sportb.webp",
        "shortDescription":  "Sporty Wear OS 3+ watch face with Big \u0026 Bold fonts, background \u0026 color styles."
    },
    {
        "appName":  "Fusion",
        "packageName":  "com.amoledwatchfaces.fusion",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 17, 2022",
        "icon":  "assets/icons/fusion.webp",
        "shortDescription":  "Fitness digital watch face for Wear OS. Gradient colors. Battery friendly."
    },
    {
        "appName":  "e-Sport",
        "packageName":  "com.amoledwatchfaces.esport",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 13, 2022",
        "icon":  "assets/icons/esport.webp",
        "shortDescription":  "Sport oriented Wear OS watch face with bold digital time. Battery friendly."
    },
    {
        "appName":  "RUN 4",
        "packageName":  "com.amoledwatchfaces.run4",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 6, 2022",
        "icon":  "assets/icons/run4.webp",
        "shortDescription":  "RUN series watch face. Big \u0026 Bold font, not OLED but optimized for all day use."
    },
    {
        "appName":  "Frontier 2",
        "packageName":  "com.amoledwatchfaces.frontier2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "May 4, 2022",
        "icon":  "assets/icons/frontier2.webp",
        "shortDescription":  "Analog Wear OS Watch face with massive watch hands. Tactical look. True blacks."
    },
    {
        "appName":  "Lean Digital",
        "packageName":  "com.amoledwatchfaces.leandigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 28, 2022",
        "icon":  "assets/icons/leandigital.webp",
        "shortDescription":  "Unique LCD digital display Wear OS watch face. Sporty look. Polished graphics."
    },
    {
        "appName":  "Talon",
        "packageName":  "com.amoledwatchfaces.talon",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 14, 2022",
        "icon":  "assets/icons/talon.webp",
        "shortDescription":  "Premium hybrid design. Choose between analog \u0026 digital. Many customizations."
    },
    {
        "appName":  "Glow Digital",
        "packageName":  "com.amoledwatchfaces.glow",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 11, 2022",
        "icon":  "assets/icons/glow.webp",
        "shortDescription":  "Premium feel digital Watch face. Glow effect. Battery friendly \u0026 pixel perfect."
    },
    {
        "appName":  "Classic 2",
        "packageName":  "com.amoledwatchfaces.ladiesclassic",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 8, 2022",
        "icon":  "assets/icons/ladiesclassic.webp",
        "shortDescription":  "Classic Watch face with 4 custom complications. Customizable. Battery friendly."
    },
    {
        "appName":  "OLED Analog Watch face",
        "packageName":  "com.watchfacestudio.awfoledanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Apr 6, 2022",
        "icon":  "assets/icons/awfoledanalog.webp",
        "shortDescription":  "OLED Studios analog watch face. Many customization options. Power efficient."
    },
    {
        "appName":  "OS 3 Digital",
        "packageName":  "com.amoledwatchfaces.os3digital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Apr 4, 2022",
        "icon":  "assets/icons/os3digital.webp",
        "shortDescription":  "Wear OS 3+ watch face. Custom complications. App shortcuts. Multiple colors."
    },
    {
        "appName":  "Binary",
        "packageName":  "com.amoledwatchfaces.binary",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Mar 29, 2022",
        "icon":  "assets/icons/binary.webp",
        "shortDescription":  "Binary Watch face. Time interpreted in binary format. For geeks \u0026 techy people."
    },
    {
        "appName":  "Fit 3",
        "packageName":  "com.amoledwatchfaces.fit3",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Mar 29, 2022",
        "icon":  "assets/icons/fit3.webp",
        "shortDescription":  "Unique digital watch face for fitness, sport. Battery friendly \u0026 pixel perfect."
    },
    {
        "appName":  "Fit OLED",
        "packageName":  "com.amoledwatchfaces.fitoled",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Mar 29, 2022",
        "icon":  "assets/icons/fitoled.webp",
        "shortDescription":  "Special OLED edition watch face. Fit series variant. 30 colors. Customizable."
    },
    {
        "appName":  "Hive",
        "packageName":  "com.amoledwatchfaces.hive",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Mar 29, 2022",
        "icon":  "assets/icons/hive.webp",
        "shortDescription":  "True black background pro edition digital watch face. Customizable \u0026 Colorful."
    },
    {
        "appName":  "Rush E",
        "packageName":  "com.amoledwatchfaces.rushe",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Mar 29, 2022",
        "icon":  "assets/icons/rushe.webp",
        "shortDescription":  "Sporty digital watch face for Wear OS devices. Battery efficient and High-res."
    },
    {
        "appName":  "Fit 5 Watch Face",
        "packageName":  "com.watchfacestudio.awffit5",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Mar 28, 2022",
        "icon":  "assets/icons/awffit5.webp",
        "shortDescription":  "Fitness oriented digital watch face for Wear OS. Colorful and customizable."
    },
    {
        "appName":  "Informer X",
        "packageName":  "com.watchfacestudio.awfinformerx",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 22, 2022",
        "icon":  "assets/icons/awfinformerx.webp",
        "shortDescription":  "Informer X digital watch face. True black background. Pixel perfect design."
    },
    {
        "appName":  "Pixel Analog",
        "packageName":  "com.watchfacestudio.awfpixelanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 16, 2022",
        "icon":  "assets/icons/awfpixelanalog.webp",
        "shortDescription":  "True black analog watch face with pixel perfect design for Wear OS"
    },
    {
        "appName":  "MNML Thin",
        "packageName":  "com.watchfacestudio.awfmnmlthin",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Mar 6, 2026",
        "releaseDate":  "Feb 15, 2022",
        "icon":  "assets/icons/awfmnmlthin.webp",
        "shortDescription":  "Simple and minimal digital watch face with a thin, modern font for Wear OS."
    },
    {
        "appName":  "Pear Analog",
        "packageName":  "com.watchfacestudio.awftrueanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Feb 10, 2022",
        "icon":  "assets/icons/awftrueanalog.webp",
        "shortDescription":  "Pear Analog. Watch face with many customization options. For Wear OS 3,4, \u0026 5."
    },
    {
        "appName":  "Wave",
        "packageName":  "com.watchfacestudio.awfwave",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 7, 2022",
        "icon":  "assets/icons/awfwave.webp",
        "shortDescription":  "Simple, black background digital watch face with a wave seconds hand for Wear OS"
    },
    {
        "appName":  "Fit Dash A",
        "packageName":  "com.watchfacestudio.awfdashboardA",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Feb 3, 2022",
        "icon":  "assets/icons/awfdashboardA.webp",
        "shortDescription":  "True black background fitness watch face for Wear OS, customizable, premium feel"
    },
    {
        "appName":  "UX Analog",
        "packageName":  "com.watchfacestudio.awfuxanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jan 26, 2022",
        "icon":  "assets/icons/awfuxanalog.webp",
        "shortDescription":  "Pixel perfect analog Watch face with many customization options for Wear OS"
    },
    {
        "appName":  "Pace 2",
        "packageName":  "com.watchfacestudio.awfpace2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jan 19, 2022",
        "icon":  "assets/icons/awfpace2.webp",
        "shortDescription":  "Sport \u0026 fitness oriented, true black background digital Watch face for Wear OS"
    },
    {
        "appName":  "Modern Minimal",
        "packageName":  "com.watchfacestudio.awfmodernminimal",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jan 17, 2022",
        "icon":  "assets/icons/awfmodernminimal.webp",
        "shortDescription":  "True black background analog / minimal PRO watch face for Wear OS."
    },
    {
        "appName":  "Digital xR",
        "packageName":  "com.watchfacestudio.awfdigitalxr",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Jan 1, 2026",
        "releaseDate":  "Jan 9, 2022",
        "icon":  "assets/icons/awfdigitalxr.webp",
        "shortDescription":  "High quality digital Wear OS Watch face with many styles and color options."
    },
    {
        "appName":  "Fit TWO",
        "packageName":  "com.watchfacestudio.awffittwo",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jan 4, 2022",
        "icon":  "assets/icons/awffittwo.webp",
        "shortDescription":  "True black background, pixel perfect, fitness digital watch face for Wear OS."
    },
    {
        "appName":  "Fit ONE",
        "packageName":  "com.watchfacestudio.awffitone",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Jan 1, 2022",
        "icon":  "assets/icons/awffitone.webp",
        "shortDescription":  "Fitness and sporty digital watch face with true black background for Wear OS."
    },
    {
        "appName":  "RUN 3",
        "packageName":  "com.watchfacestudio.awfrun3",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 20, 2021",
        "icon":  "assets/icons/awfrun3.webp",
        "shortDescription":  "Digital, sporty and battery friendly watch face with true black background."
    },
    {
        "appName":  "LCD Digital",
        "packageName":  "com.watchfacestudio.awflcddigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 14, 2021",
        "icon":  "assets/icons/awflcddigital.webp",
        "shortDescription":  "True black background watch face for Wear OS. LCD display font. Pixel perfect."
    },
    {
        "appName":  "Hike ONE",
        "packageName":  "com.watchfacestudio.awfhikeone",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 13, 2021",
        "icon":  "assets/icons/awfhikeone.webp",
        "shortDescription":  "True black background, big and bold font watch face for Wear OS"
    },
    {
        "appName":  "Sporty Digital",
        "packageName":  "com.watchfacestudio.awfsportydigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 8, 2021",
        "icon":  "assets/icons/awfsportydigital.webp",
        "shortDescription":  "True black background, pixel perfect fitness watch face for Wear OS."
    },
    {
        "appName":  "TRON Dark",
        "packageName":  "com.watchfacestudio.awftrondark",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 7, 2021",
        "icon":  "assets/icons/awftrondark.webp",
        "shortDescription":  "True black background TRON inspired digital watch face for Wear OS"
    },
    {
        "appName":  "TACT x",
        "packageName":  "com.watchfacestudio.awftactical",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 5, 2021",
        "icon":  "assets/icons/awftactical.webp",
        "shortDescription":  "Tactical \u0026 military - army, black BG digital Watch face for Wear OS."
    },
    {
        "appName":  "Active xV",
        "packageName":  "com.watchfacestudio.awfactivexv",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Dec 1, 2021",
        "icon":  "assets/icons/awfactivexv.webp",
        "shortDescription":  "True black background digital watch face with high readable font for Wear OS"
    },
    {
        "appName":  "InfoGraph",
        "packageName":  "com.watchfacestudio.awfinfograph",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 29, 2021",
        "icon":  "assets/icons/awfinfograph.webp",
        "shortDescription":  "True black background Infograph digital Watch face for Wear OS"
    },
    {
        "appName":  "SPORT xR",
        "packageName":  "com.watchfacestudio.awfsportxr",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "May 4, 2026",
        "releaseDate":  "Nov 25, 2021",
        "icon":  "assets/icons/awfsportxr.webp",
        "shortDescription":  "Sport \u0026 fitness digital watch face designed for active lifestyles."
    },
    {
        "appName":  "Owly",
        "packageName":  "com.watchfacestudio.awfowly",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 23, 2021",
        "icon":  "assets/icons/awfowly.webp",
        "shortDescription":  "Hoot Hoot! Unique, artistic \u0026 customizable watch face with a sleek owl look"
    },
    {
        "appName":  "Health",
        "packageName":  "com.watchfacestudio.awfhealthface",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 18, 2021",
        "icon":  "assets/icons/awfhealthface.webp",
        "shortDescription":  "True black background, health oriented digital watch face for Wear OS."
    },
    {
        "appName":  "Terminal",
        "packageName":  "com.watchfacestudio.awfterminal",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 16, 2021",
        "icon":  "assets/icons/awfterminal.webp",
        "shortDescription":  "True black background, terminal, geek - programmer watch face for Wear OS."
    },
    {
        "appName":  "Dash Digital",
        "packageName":  "com.watchfacestudio.awfdashdigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "May 5, 2026",
        "releaseDate":  "Nov 15, 2021",
        "icon":  "assets/icons/awfdashdigital.webp",
        "shortDescription":  "True black background multicolor, digital fitness Watch face for Wear OS"
    },
    {
        "appName":  "Dash Analog",
        "packageName":  "com.watchfacestudio.awfdashanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 12, 2021",
        "icon":  "assets/icons/awfdashanalog.webp",
        "shortDescription":  "True black background fitness analog Watch face with gradient color bars"
    },
    {
        "appName":  "Parts",
        "packageName":  "com.watchfacestudio.awfparts",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 10, 2021",
        "icon":  "assets/icons/awfparts.webp",
        "shortDescription":  "Digital, true black background and customizable watch face for Wear OS."
    },
    {
        "appName":  "Casual",
        "packageName":  "com.watchfacestudio.awfcasual",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 8, 2021",
        "icon":  "assets/icons/awfcasual.webp",
        "shortDescription":  "True black background watch face for Wear OS."
    },
    {
        "appName":  "Motion 0x",
        "packageName":  "com.watchfacestudio.awfmotion0x",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 3, 2021",
        "icon":  "assets/icons/awfmotion0x.webp",
        "shortDescription":  "True black background sportive lifestyle analog watch face for Wear OS."
    },
    {
        "appName":  "MNML Glow",
        "packageName":  "com.watchfacestudio.awfmnmlglow",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Nov 1, 2021",
        "icon":  "assets/icons/awfmnmlglow.webp",
        "shortDescription":  "True black background minimal glowing effect digital Watch face for Wear OS"
    },
    {
        "appName":  "Fit Dashboard",
        "packageName":  "com.watchfacestudio.awfdashboard",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Oct 28, 2021",
        "icon":  "assets/icons/awfdashboard.webp",
        "shortDescription":  "True black BG, fitness oriented \u0026 battery friendly Watch face for Wear OS"
    },
    {
        "appName":  "Analog 2",
        "packageName":  "com.watchfacestudio.awfladiesanalog2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 25, 2021",
        "icon":  "assets/icons/awfladiesanalog2.webp",
        "shortDescription":  "Premium and customizable battery friendly analog watch face for Wear OS."
    },
    {
        "appName":  "Minimal",
        "packageName":  "com.watchfacestudio.awfminimal",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Oct 23, 2021",
        "icon":  "assets/icons/awfminimal.webp",
        "shortDescription":  "True black background, minimal and battery friendly watch face for Wear OS."
    },
    {
        "appName":  "Classic",
        "packageName":  "com.watchfacestudio.awfclassicface",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 20, 2021",
        "icon":  "assets/icons/awfclassicface.webp",
        "shortDescription":  "True black background classic and customizable analog watch face for Wear OS."
    },
    {
        "appName":  "Tic",
        "packageName":  "com.watchfacestudio.awftic",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Oct 18, 2021",
        "icon":  "assets/icons/awftic.webp",
        "shortDescription":  "Hybrid Watch face with custom complications \u0026 customizable, sporty look."
    },
    {
        "appName":  "Clean Digital",
        "packageName":  "com.watchfacestudio.awfcleandigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 12, 2021",
        "icon":  "assets/icons/awfcleandigital.webp",
        "shortDescription":  "True black background and sporty digital watch face for Wear OS."
    },
    {
        "appName":  "Anjuna",
        "packageName":  "com.watchfacestudio.awfanjuna",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 11, 2021",
        "icon":  "assets/icons/awfanjuna.webp",
        "shortDescription":  "True black background hybrid and customizable watch face for Wear OS watches."
    },
    {
        "appName":  "Digital 1",
        "packageName":  "com.watchfacestudio.awfdigital1",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 11, 2021",
        "icon":  "assets/icons/awfdigital1.webp",
        "shortDescription":  "True black background, Wear OS watch face with big digital numbers."
    },
    {
        "appName":  "Ladies RUN",
        "packageName":  "com.watchfacestudio.awfladiesrun",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 6, 2021",
        "icon":  "assets/icons/awfladiesrun.webp",
        "shortDescription":  "RUN - sporty Wear OS watch face variant - made especially for ladies and women!"
    },
    {
        "appName":  "Polar Event",
        "packageName":  "com.watchfacestudio.awfpolarevent",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 4, 2021",
        "icon":  "assets/icons/awfpolarevent.webp",
        "shortDescription":  "Battery friendly watch face with the Next Event / Schedule complication."
    },
    {
        "appName":  "One",
        "packageName":  "com.watchfacestudio.awfone",
        "isAvailable":  true,
        "isFree":  true,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Oct 1, 2021",
        "icon":  "assets/icons/awfone.webp",
        "shortDescription":  "True black background \u0026 battery friendly Watch face for Wear OS"
    },
    {
        "appName":  "Lines",
        "packageName":  "com.watchfacestudio.awflines",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Sep 30, 2021",
        "icon":  "assets/icons/awflines.webp",
        "shortDescription":  "Unique Text Time watch face with beautiful colors. Read time without numbers."
    },
    {
        "appName":  "Active Analog",
        "packageName":  "com.watchfacestudio.awfactiveanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 29, 2021",
        "icon":  "assets/icons/awfactiveanalog.webp",
        "shortDescription":  "True black background and battery friendly watch face for Wear OS."
    },
    {
        "appName":  "Modern Analog",
        "packageName":  "com.watchfacestudio.awflmoderna",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 24, 2021",
        "icon":  "assets/icons/awflmoderna.webp",
        "shortDescription":  "Modern stylish and unique analog watch face. Made especially for ladies."
    },
    {
        "appName":  "RUN 2",
        "packageName":  "com.watchfacestudio.awfrun2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 21, 2021",
        "icon":  "assets/icons/awfrun2.webp",
        "shortDescription":  "True black background, sporty \u0026 battery friendly #watchface for Wear OS"
    },
    {
        "appName":  "Sporty Analog",
        "packageName":  "com.watchfacestudio.awfsportyanalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 20, 2021",
        "icon":  "assets/icons/awfsportyanalog.webp",
        "shortDescription":  "True black background, sporty and battery friendly analog watch face for Wear OS"
    },
    {
        "appName":  "Mohawk",
        "packageName":  "com.watchfacestudio.awfmohawk",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 18, 2021",
        "icon":  "assets/icons/awfmohawk.webp",
        "shortDescription":  "True black background and battery friendly digital watch face for Wear OS."
    },
    {
        "appName":  "Health Dx",
        "packageName":  "com.watchfacestudio.awfhealthd",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Sep 13, 2021",
        "icon":  "assets/icons/awfhealthd.webp",
        "shortDescription":  "True black background \u0026 battery friendly health focused Watch face for Wear OS"
    },
    {
        "appName":  "Polar Analog",
        "packageName":  "com.watchfacestudio.awfpolaranalog",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 9, 2021",
        "icon":  "assets/icons/awfpolaranalog.webp",
        "shortDescription":  "True black background and battery friendly analog watch face for Wear OS."
    },
    {
        "appName":  "Pixel",
        "packageName":  "com.watchfacestudio.awfpixelface",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 7, 2021",
        "icon":  "assets/icons/awfpixelface.webp",
        "shortDescription":  "Minimal, customizable \u0026 battery friendly pixel style watch face for Wear OS."
    },
    {
        "appName":  "RUN PRO",
        "packageName":  "com.watchfacestudio.awfrun",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 7, 2021",
        "icon":  "assets/icons/awfrun.webp",
        "shortDescription":  "True black background, fitness and battery friendly watch face for Wear OS."
    },
    {
        "appName":  "Outback",
        "packageName":  "com.watchfacestudio.awfoutback",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 2, 2021",
        "icon":  "assets/icons/awfoutback.webp",
        "shortDescription":  "True black background and battery friendly watch face for Wear OS"
    },
    {
        "appName":  "Polar",
        "packageName":  "com.watchfacestudio.awfpolar",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Sep 1, 2021",
        "icon":  "assets/icons/awfpolar.webp",
        "shortDescription":  "True black background, battery friendly digital watch face with gradient colors."
    },
    {
        "appName":  "Dynamic PRO",
        "packageName":  "com.watchfacestudio.awfdynamicpro",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 30, 2021",
        "icon":  "assets/icons/awfdynamicpro.webp",
        "shortDescription":  "True black background \u0026 battery friendly digital watch face for Wear OS."
    },
    {
        "appName":  "Move",
        "packageName":  "com.watchfacestudio.awfmovehyb",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Aug 29, 2021",
        "icon":  "assets/icons/awfmovehyb.webp",
        "shortDescription":  "True black background and battery friendly hybrid watch face for Wear OS."
    },
    {
        "appName":  "Pace PRO",
        "packageName":  "com.watchfacestudio.awfpacepro",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 26, 2021",
        "icon":  "assets/icons/awfpacepro.webp",
        "shortDescription":  "True black background sporty \u0026 battery friendly Watch face for Wear OS"
    },
    {
        "appName":  "n-Digital 2",
        "packageName":  "com.watchfacestudio.awfnewdigital2",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 25, 2021",
        "icon":  "assets/icons/awfnewdigital2.webp",
        "shortDescription":  "True black background \u0026 battery friendly Watch face for Wear OS"
    },
    {
        "appName":  "Aeon e-BPM",
        "packageName":  "com.watchfacestudio.awfaeonbpm",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  true,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 23, 2021",
        "icon":  "assets/icons/awfaeonbpm.webp",
        "shortDescription":  "True black background, battery friendly analog Watch face for Wear OS"
    },
    {
        "appName":  "SPORT xDark",
        "packageName":  "com.watchfacestudio.sportxdark",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 3, 2025",
        "releaseDate":  "Aug 19, 2021",
        "icon":  "assets/icons/sportxdark.webp",
        "shortDescription":  "True black background, sporty and battery friendly watch face for Wear OS."
    },
    {
        "appName":  "n-Digital",
        "packageName":  "com.watchfacestudio.awfnewdigital",
        "isAvailable":  true,
        "isFree":  false,
        "isAnalog":  false,
        "hasWeather":  false,
        "lastUpdated":  "Dec 2, 2025",
        "releaseDate":  "Aug 12, 2021",
        "icon":  "assets/icons/awfnewdigital.webp",
        "shortDescription":  "True black background \u0026 battery friendly Watch face for Wear OS"
    }
];

if (typeof window !== 'undefined') {
  window.portfolio = portfolio;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { portfolio };
}

