"""
scripts/descriptions_fr.py
Clean, idiomatic, professional French short descriptions for all 226 watch faces and apps.
"""

DESCRIPTIONS_FR = {
    "adventurer2": "Bientôt disponible...",
    "ultra2": "Cadran élégant et hautement personnalisable, inspiré du style analogique de la Galaxy Watch Ultra 2.",
    "matte": "Cadran simple et élégant avec grande horloge numérique et complications personnalisées.",
    "military2": "Esthétique tactique, police numérique LCD améliorée et nombreuses options de personnalisation.",
    "vertex": "Disposition circulaire avec 8 complications personnalisables. Simple, épuré et efficace.",
    "zenith": "7 emplacements de complications personnalisées, météo, barres de progression en dégradé et plus encore.",
    "gravity": "Conçu dans le style natif de Wear OS. Hautement personnalisable et économe en batterie.",
    "epoch": "Cadran analogique raffiné avec anneaux de date dynamiques et complications personnalisables.",
    "grid": "Uniquement des complications personnalisées, rien de superflu.",
    "digest": "Deux grands emplacements de complications pour visualiser un maximum d'informations d'un seul coup d'œil.",
    "expedition": "Un cadran ultra-informatif doté de 8 emplacements de complications personnalisables.",
    "utility": "Cadran Material Design hautement personnalisable avec 8 complications au choix.",
    "rugged2": "Conçu pour les conditions extrêmes avec un affichage imposant de l'heure et des complications sur mesure.",
    "weatherDashboard": "Météo actuelle, prévisions complètes, indice UV, probabilité de pluie et complications personnalisées.",
    "pixelAnalog2": "Cadran personnalisable doté d'une horloge analogique compacte et élégante.",
    "wayfarer": "Cadran analogique économe en énergie et hautement personnalisable. Adaptez-le à votre style.",
    "vibe": "Cadran compact et économe en batterie avec disposition radiale des complications.",
    "circleDashboard": "Cadran moderne et personnalisable inspiré du tableau de bord circulaire de la Galaxy Watch.",
    "everyday": "Cadran expressif Material 3, simple, minimaliste et entièrement personnalisable.",
    "eccentric": "Cadran moderne avec des polices numériques distinctives et de nombreuses options de style.",
    "adaptive": "Cadran numérique économe en énergie, au design moderne, fluide et personnalisable.",
    "pilot": "Cadran hybride avec barres de progression en arc pointillé et esthétique aéronautique.",
    "expressive": "Cadran au style Material Expressive avec une multitude de configurations et de couleurs.",
    "auroraAnalog": "Cadran analogique interactif dont les aurores boréales réagissent aux mouvements du poignet.",
    "nova": "Cadran futuriste et personnalisable avec des combinaisons de thèmes infinies.",
    "trackMate": "Cadran sportif et épuré affichant vos données essentielles en un instant.",
    "haze": "Léger, minimaliste et décontracté. Traversez les belles journées d'été avec style.",
    "peakShadow": "Inspiré par la nature. Un cadran unique, haut en couleur et personnalisable.",
    "apex2": "Deuxième version du design Apex, enrichie de prévisions météo horaires et quotidiennes.",
    "tact5": "Cadran tactique moderne avec 8 emplacements de complications et des thèmes exclusifs.",
    "explorer": "Cadran analogique classique avec 8 complications personnalisées et de superbes palettes de couleurs.",
    "boost": "Cadran axé sur le fitness avec d'élégantes barres de couleur et une haute lisibilité.",
    "stealth": "Cadran furtif et personnalisable : thèmes sombres, complications et polices sélectionnables.",
    "military": "Police d'horloge LCD exclusive conçue sur mesure, avec de multiples styles et teintes.",
    "roto": "Cadran unique et dynamique dont la disposition pivote subtilement chaque minute.",
    "outdoor": "Cadran coloré, informatif et robuste pour toutes vos aventures en plein air.",
    "glide": "Grande horloge numérique audacieuse, complications personnalisées et design contemporain.",
    "compact": "Cadran fin et moderne avec 8 complications, polices au choix et thèmes variés.",
    "soft": "Cadran minimaliste d'une lisibilité exemplaire avec l'essentiel des complications.",
    "ultra": "Cadran moderne et modulable inspiré de l'esthétique analogique de la Galaxy Watch Ultra.",
    "maverick": "Le temps réinventé. Maverick est votre compagnon personnalisable pour les défis du quotidien.",
    "radial": "Horloge numérique entourée de 8 complications circulaires avec polices au choix.",
    "kinetic": "Cadran élégant et dynamique avec thèmes riches, complications et mode sombre optimisé.",
    "aurora": "Cadran minimaliste aux aurores boréales envoûtantes réactives aux mouvements du poignet.",
    "weatherAnalog": "Suivez la météo actuelle et les prévisions sur 10 heures dans un design analogique épuré.",
    "forecast": "Prévisions météo complètes : conditions horaires, température, indice UV et probabilité de pluie.",
    "summit": "Complications personnalisables, allure soignée, modes horaires et options de style infinies.",
    "pioneer": "Doté de thèmes Material, de polices soignées et de 8 complications pour une flexibilité totale.",
    "pathfinder": "Cadran analogique avec thèmes personnalisables, styles d'aiguilles et complications.",
    "halo": "Cadran moderne et complet : associez librement couleurs, polices et complications.",
    "spooky": "Ambiance d'Halloween amusante et mystérieuse avec de nombreuses fonctions pratiques.",
    "infoHub": "Votre centre d'information personnel avec 6 complications modulables et plusieurs thèmes.",
    "textTime": "Cadran textuel multicolore et multilingue pour lire l'heure sous forme de mots.",
    "adventurer": "Cadran riche et complet inspiré du design Active de la Pixel Watch 3.",
    "breezy": "Cadran frais et décontracté : personnalisez les couleurs, les dégradés et les complications.",
    "symmetrical": "Composez un cadran parfaitement équilibré grâce à ses emplacements symétriques.",
    "weather": "Météo en direct, prévisions, probabilité de pluie, indice UV et deux complications dédiées.",
    "mainGoals": "Design pensé pour vos objectifs quotidiens : polices au choix et thèmes Material You.",
    "analogm4": "Cadran Material You moderne avec 8 complications, styles d'aiguilles et finitions variées.",
    "binary2": "Cadran binaire sexagésimal innovant. Touchez l'écran pour afficher l'heure numérique !",
    "apex": "Cadran personnalisable avec polices au choix, dégradés colorés et complications utiles.",
    "inverted": "Regardez le temps s'animer au rythme des secondes qui remplissent l'horloge numérique.",
    "classicm5": "Créez votre cadran classique idéal avec plus de 60 combinaisons de couleurs et de styles.",
    "streamlined": "Animation fluide de l'horloge numérique, 6 complications et deux modes d'affichage.",
    "perpetual": "Design numérique basse consommation, propulsé par le Watch Face Format de Google.",
    "outlined": "Polices avec contour personnalisables, format Watch Face Format et consommation minimale.",
    "classicm3": "Inspiré du célèbre cadran Classique de la Pixel Watch, optimisé et entièrement personnalisable.",
    "nomad": "L'esprit digital nomade au poignet avec ce cadran élégant, moderne et fonctionnel.",
    "timeMode": "4 modes horaires, 8 complications personnalisées et grande efficacité énergétique.",
    "timeFlow": "Design fluide et novateur sur fond noir absolu, optimisé pour l'autonomie de la batterie.",
    "arcsd5": "Version numérique Arcs avec polices personnalisables et 8 complications complètes.",
    "basicAnalog": "Cadran analogique épuré inspiré de l'animation de démarrage du Watch Face Format.",
    "arcsn6": "Cadran analogique Watch Face Format avec de superbes arcs de progression en dégradé.",
    "widgets2": "8 complications, polices horaires uniques et harmonies de couleurs élégantes.",
    "horizon9": "Cadran numérique OLED à affichage 7 segments avec 6 complications optimisées.",
    "nord": "Conçu avec Watch Face Format 2 : personnalisation sans limites et 8 complications.",
    "gamerv1": "Pour les passionnés de jeux vidéo : police rétro, créatures pixelisées et look unique.",
    "manager": "Boostez votre productivité avec ce cadran professionnel, épuré et économe en énergie.",
    "active2": "Design orienté fitness avec fond noir absolu et complications dédiées à la forme.",
    "dualtone": "Thèmes bicolores saisissants avec effet de lueur sur l'horloge numérique.",
    "infograph2": "Cadran numérique riche en informations pour toutes les montres connectées Wear OS 4+.",
    "infoblock2": "Barres de progression en dégradé et 8 complications complètes dans un format basse consommation.",
    "analogm3": "Cadran analogique au design Material 3 avec aiguilles et couleurs entièrement personnalisables.",
    "glancex": "Toutes vos données d'un coup d'œil. Rendu splendide sur Pixel Watch et montres rondes.",
    "favoriteappstile": "Fini le défilement dans la liste d'applications : lancez vos favoris via une Tuile dédiée !",
    "lucid": "Lisibilité exceptionnelle, esthétique Material Design et consommation de batterie ultra-faible.",
    "weathercomplications": "Complications météo avancées pour Wear OS : UV, température min/max, qualité de l'air et plus.",
    "chrono": "Cadran hybride avec 7 complications, multiples thèmes et optimisation d'autonomie.",
    "react2": "Deuxième édition du design React : allure contemporaine, réactivité et modularité.",
    "modular": "Conception modulaire soignée avec polices sélectionnables et précision au pixel près.",
    "sprint": "Cadran sportif créé avec le Watch Face Format, pensé pour la vitesse et l'autonomie.",
    "hugetime": "Heure numérique grand format pour une lecture immédiate et 6 complications pratiques.",
    "controldash": "Tableau de bord de productivité avec 6 complications sur fond noir pur OLED.",
    "angular": "Lignes angulaires affirmées, 7 complications et fond noir absolu économe en batterie.",
    "pulse2": "Cadran numérique santé et fitness avec quatre emplacements de données sur fond noir pur.",
    "rugged": "Robuste, grand format et résistant, avec de multiples emplacements d'informations.",
    "pride": "Célébrez la diversité avec les drapeaux et symboles arc-en-ciel LGBTQ+ sur Wear OS.",
    "tactthree": "Cadran tactique pour Wear OS 3 et 4 (API 30+), robuste et économe en batterie.",
    "materialyou2": "Seconde édition Material You avec deux barres de progression et fonds mesh texturés.",
    "material4": "Cadran numérique haute résolution à l'allure moderne et à très faible consommation.",
    "pacifice": "Version perfectionnée du design Pacific, compatible avec tous les appareils Wear OS.",
    "engine": "Cadran numérique haut de gamme au look mécanique haute précision.",
    "concentric1": "Cadran numérique concentrique, économe en batterie et parfait pour les écrans OLED.",
    "nanox1": "Design hybride coloré et original alliant aiguilles classiques et affichage numérique.",
    "digitalinformer": "Cadran Material Design informatif, personnalisable et très respectueux de la batterie.",
    "tempo": "Allure dynamique et sportive avec complications modulables et styles de couleurs variés.",
    "alpine": "Cadran hybride avec grande horloge numérique et 8 complications pour la montagne et la ville.",
    "photowatchface": "Affichez vos photos préférées au poignet parmi une sélection ou depuis votre galerie.",
    "photocomplication": "Complication photo pour cadrans Wear OS : choisissez n'importe quelle image de votre galerie.",
    "nitrous": "Design analogique racé avec de nombreuses complications et un profil basse consommation.",
    "react": "Cadran Wear OS économe en énergie avec de nombreuses palettes de couleurs et complications.",
    "guard": "Cadran numérique net, précis et protecteur de l'autonomie de votre montre.",
    "marine": "Inspiration nautique haut de gamme, précision au pixel près et faible consommation.",
    "mnmlanalog": "L'essence même du minimalisme analogique : sobre, élégant et économe en batterie.",
    "xface": "Suivez votre fréquence cardiaque en direct dans un cadran clair et réactif.",
    "tacttwo": "Cadran tactique haute précision à très faible consommation d'énergie.",
    "infoblock": "Inspiré de la présentation par blocs d'informations, personnalisable et pratique.",
    "circuit": "Inspiration circuits électroniques sur fond noir pur avec 7 complications et 30 thèmes.",
    "progress": "Cadran avant-gardiste où le temps qui passe est représenté par des barres de progression.",
    "analogpro": "Cadran analogique professionnel et moderne, entièrement personnalisable.",
    "athlete2lite": "Version allégée d'Athlete 2 avec barres en dégradé et complications essentielles.",
    "athlete2": "Dédié au sport et aux performances sur Wear OS 3+, optimisé et personnalisable.",
    "pulse": "Suivi complet de vos constantes, barres de dégradé et fond noir OLED économe.",
    "pixeloled": "Style Material You inspiré de la Pixel Watch avec complications personnalisables.",
    "hyb": "Heures numériques en grand dégradé et barres de progression pour les minutes et secondes.",
    "analogxt": "Cadran analogique simple, lisible et épuré pour Wear OS.",
    "fitx": "Cadran dédié à la santé et au fitness, personnalisable et pensé pour l'autonomie.",
    "slimdigital": "Heure numérique fine et lisible sur fond noir pur OLED avec complications intégrées.",
    "simpleanalog": "Cadran analogique sobre au style Material Design avec fond noir absolu.",
    "widgets1": "8 complications personnalisables dans un cadran Wear OS économe en énergie.",
    "bigdigital": "Grande heure numérique facile à lire, taille d'application légère et haute autonomie.",
    "weatherdigital": "Horloge numérique grand format accompagnée d'une grande complication météo détaillée.",
    "materialyou": "Créé pour Wear OS selon les principes Material You : adaptatif et économe en batterie.",
    "healthface2": "Cadran santé et bien-être pour montres connectées Wear OS avec suivi en direct.",
    "xviper": "Cadran analogique moderne et audacieux avec complications et faible consommation.",
    "pace3": "Cadran fitness avec deux complications de progression à intervalle personnalisables.",
    "gradient": "Animations en dégradé harmonieuses, grande police numérique et fond noir pur.",
    "material3": "Design Material 3 avec intégration poussée des complications et thèmes dynamiques.",
    "tactq": "Allure tactique militaire avec fonds de camouflage interchangeables.",
    "retro": "Inspiration numérique rétro des années 80 dans un format moderne et économe.",
    "edge": "Cadran net et épuré avec complications essentielles, idéal pour les dalles OLED.",
    "sportive": "Cadran haut de gamme alliant haute résolution, allure athlétique et autonomie.",
    "simpledigital": "Affichage numérique direct, lisible et pensé pour préserver votre batterie.",
    "catalyst": "Porté avec succès depuis Tizen OS : rendu premium, finitions nettes et personnalisation.",
    "athlete1": "Cadran orienté santé pour les sportifs exigeants et les amateurs d'activités physiques.",
    "hscomplications": "Complications santé avancées : distance, étages, calories, pas et fréquence cardiaque.",
    "weekdayutccomp": "Ensemble de complications personnalisées utiles affichant le jour de la semaine et l'heure UTC.",
    "tactone": "Cadran tactique avec affichage numérique, atténuateur de luminosité et fond noir pur.",
    "sportb": "Cadran sportif pour Wear OS 3+ avec grands chiffres gras et styles d'arrière-plan variés.",
    "fusion": "Cadran fitness numérique aux couleurs en dégradé avec optimisation d'énergie.",
    "esport": "Conçu pour l'e-sport et les athlètes : grands chiffres numériques et haute lisibilité.",
    "run4": "Série RUN : typographie imposante et contraste maximal pensé pour vos sessions d'entraînement.",
    "frontier2": "Cadran analogique avec aiguilles imposantes, allure baroudeuse et noirs profonds.",
    "leandigital": "Écran numérique LCD distinctif au look sportif et aux graphismes soignés.",
    "talon": "Design hybride luxueux : basculez aisément entre affichage analogique et numérique.",
    "glow": "Cadran numérique sophistiqué avec effet lumineux subtil et précision au pixel près.",
    "ladiesclassic": "Cadran classique et raffiné doté de 4 complications personnalisées.",
    "awfoledanalog": "Cadran analogique signé OLED Studios, hautement personnalisable et économe.",
    "os3digital": "Cadran Wear OS 3+ avec raccourcis d'applications, complications et multiples coloris.",
    "hive": "Édition Pro numérique sur fond noir pur avec motifs alvéolés et couleurs riches.",
    "binary": "Interprétation binaire de l'heure : idéal pour les technophiles et les passionnés de code.",
    "fit3": "Cadran numérique unique pour vos entraînements : léger, net et parfaitement calibré.",
    "rushe": "Allure sportive et nerveuse pour Wear OS avec graphismes haute définition.",
    "fitoled": "Édition spéciale OLED de la gamme Fit : 30 coloris et personnalisation complète.",
    "awffit5": "Cadran fitness dynamique pour Wear OS, riche en couleurs et en options.",
    "awfinformerx": "Cadran Informer X sur fond noir pur : clarté exemplaire et données en temps réel.",
    "awfpixelanalog": "Cadran analogique noir absolu avec rendu impeccable au pixel près.",
    "awfmnmlthin": "Cadran numérique minimaliste avec une typographie fine et contemporaine.",
    "awftrueanalog": "Poire analogique : cadran raffiné aux nombreuses possibilités de personnalisation.",
    "awfwave": "Horloge numérique élégante avec trotteuse ondulée originale sur fond noir OLED.",
    "awfdashboardA": "Tableau de bord de fitness sur fond noir pur avec une finition résolument premium.",
    "awfuxanalog": "Cadran analogique au design soigné offrant de nombreuses options de personnalisation.",
    "awfpace2": "Cadran numérique orienté sport et endurance sur fond noir absolu.",
    "awfmodernminimal": "Cadran Pro minimaliste combinant aiguilles et fond noir pur OLED.",
    "awfdigitalxr": "Cadran numérique Wear OS de qualité supérieure avec une foule de styles et de teintes.",
    "awffittwo": "Précision millimétrée et suivi d'entraînement complet sur fond noir pur.",
    "awffitone": "Cadran numérique alliant sportivité et économie d'énergie pour vos journées actives.",
    "awfrun3": "Cadran de course numérique, endurant et contrasté pour un confort de lecture optimal.",
    "awflcddigital": "Affichage à cristaux liquides rétro sur fond noir profond pour Wear OS.",
    "awfhikeone": "Conçu pour la randonnée : chiffres grands et gras lisibles en plein soleil.",
    "awfsportydigital": "Cadran fitness précis et percutant, optimisé pour les écrans AMOLED.",
    "awftrondark": "Inspiration science-fiction et univers TRON sur fond noir absolu pour Wear OS.",
    "awftactical": "Inspiration militaire et tactique avec affichage numérique net et robuste.",
    "awfactivexv": "Typographie haute lisibilité pour ce cadran numérique économe en batterie.",
    "awfinfograph": "Style infographique complet affichant toutes vos métriques essentielles.",
    "awfsportxr": "Cadran numérique pensé pour accompagner votre mode de vie dynamique.",
    "awfowly": "Un chouette cadran artistique et original au regard expressif et personnalisable.",
    "awfhealthface": "Cadran numérique axé sur vos paramètres de santé et votre activité physique.",
    "awfterminal": "Inspiration invite de commande et terminal Linux pour les développeurs et geeks.",
    "awfdashdigital": "Tableau de bord multicolore sur fond noir OLED avec suivi d'activité.",
    "awfdashanalog": "Cadran analogique de remise en forme avec jauges courbées en dégradé de couleurs.",
    "awfparts": "Composants numériques modulables sur fond noir profond pour Wear OS.",
    "awfcasual": "Cadran polyvalent et sobre sur fond noir pur, idéal au quotidien.",
    "awfmotion0x": "Allure sportive et active dans un cadran analogique à fort contraste.",
    "awfmnmlglow": "Effet de lueur minimaliste sur fond noir absolu pour une ambiance nocturne soignée.",
    "awfdashboard": "Cadran orienté bien-être et entraînement, conçu pour durer toute la journée.",
    "awfladiesanalog2": "Cadran analogique féminin haut de gamme, personnalisable et respectueux de la batterie.",
    "awfminimal": "L'élégance du minimalisme absolu sur fond noir pur avec consommation minimale.",
    "awfclassicface": "Élégance intemporelle d'un cadran analogique traditionnel sur fond sombre.",
    "awftic": "Cadran hybride équilibré avec complications personnalisées et allure sportive.",
    "awfcleandigital": "Affichage numérique net, précis et dynamique sur fond noir pur.",
    "awfdigital1": "Grands chiffres numériques très visibles pour une lecture instantanée de l'heure.",
    "awfanjuna": "Cadran hybride aux superbes nuances d'éclairage sur fond noir absolu.",
    "phonebattcomp": "Complication Wear OS indiquant le niveau de batterie de votre smartphone (en %).",
    "awfladiesrun": "Variante sportive de la série RUN conçue spécialement pour les femmes.",
    "awfpolarevent": "Gardez une longueur d'avance sur votre journée grâce à la complication du prochain événement.",
    "awfone": "Sobriété, fond noir pur et excellente gestion de l'énergie sur Wear OS.",
    "awflines": "Affichage unique de l'heure en toutes lettres avec de superbes thèmes de couleurs.",
    "awfactiveanalog": "Cadran analogique tonique et économe en énergie pour vos activités quotidiennes.",
    "awflmoderna": "Cadran analogique moderne, chic et distinctif conçu pour les poignets féminins.",
    "awfrun2": "Cadran de course endurant et contrasté pour Wear OS, pensé pour la performance.",
    "awfsportyanalog": "Cadran analogique au tempérament sportif avec noirs intenses et faible consommation.",
    "awfmohawk": "Cadran numérique original et percutant, conçu pour préserver la batterie.",
    "awfhealthd": "Surveillez vos données de santé avec ce cadran soigné sur fond noir pur.",
    "awfpolaranalog": "Design analogique épuré et sobre garantissant une excellente autonomie.",
    "awfpixelface": "Graphismes pixel art minimalistes et consommation d'énergie maîtrisée.",
    "awfrun": "Le cadran originel de la série RUN : lisibilité optimale et endurance assurée.",
    "awfoutback": "Prêt pour les grands espaces avec son contraste élevé et sa faible consommation.",
    "awfpolar": "Dégradés de couleurs subtils sur fond noir profond pour ce cadran numérique fluide.",
    "awfdynamicpro": "Affichage numérique dynamique et modulable conçu pour les montres Wear OS.",
    "awfmovehyb": "Combinaison harmonieuse d'aiguilles et de données numériques sur fond noir pur.",
    "awfpacepro": "Cadran athlétique haute performance pensé pour préserver votre batterie.",
    "awfnewdigital2": "Horloge numérique moderne, fond noir absolu et efficacité énergétique prouvée.",
    "awfaeonbpm": "Cadran analogique avec indicateur de rythme cardiaque sur fond noir OLED.",
    "sportxdark": "Cadran sportif sombre et contrasté, parfaitement optimisé pour Wear OS.",
    "awfnewdigital": "L'essentiel du numérique avec fond noir pur et excellente autonomie."
}
