"""
scripts/descriptions_pt.py
Clean, idiomatic, professional Portuguese short descriptions for all 226 watch faces and apps.
"""

DESCRIPTIONS_PT = {
    "adventurer2": "Disponível em breve...",
    "ultra2": "Mostrador elegante e altamente personalizável, inspirado no estilo analógico do Galaxy Watch Ultra 2.",
    "matte": "Mostrador simples e estiloso com grande relógio digital e complicações personalizadas.",
    "military2": "Estética tática, fonte digital LCD aprimorada e amplas opções de personalização.",
    "vertex": "Layout circular com 8 complicações personalizáveis. Simples, limpo e eficiente.",
    "zenith": "7 slots de complicações, clima detalhado, barras de progresso em gradiente e muito mais.",
    "gravity": "Projetado com o visual nativo do Wear OS. Altamente personalizável e econômico na bateria.",
    "epoch": "Mostrador analógico sofisticado com anéis dinâmicos de data e complicações personalizadas.",
    "grid": "Apenas complicações personalizadas, sem distrações.",
    "digest": "Dois grandes slots de complicações para você visualizar o máximo de informações num relance.",
    "expedition": "Um mostrador ultra-informativo com 8 slots de complicações personalizáveis.",
    "utility": "Mostrador em estilo Material Design altamente personalizável com 8 complicações à sua escolha.",
    "rugged2": "Construído para condições extremas com horário marcante em destaque e complicações robustas.",
    "weatherDashboard": "Clima atual, previsão completa, índice UV, probabilidade de chuva e complicações.",
    "pixelAnalog2": "Mostrador personalizável com um relógio analógico compacto e elegante.",
    "wayfarer": "Design analógico econômico e altamente personalizável. Deixe-o com o seu estilo.",
    "vibe": "Mostrador compacto e eficiente com disposição radial dos slots de complicações.",
    "circleDashboard": "Mostrador moderno e personalizável inspirado no Circle Dashboard do Galaxy Watch.",
    "everyday": "Mostrador expressivo no estilo Material 3, simples, minimalista e totalmente personalizável.",
    "eccentric": "Mostrador moderno com fontes digitais marcantes e diversas opções de estilo.",
    "adaptive": "Mostrador digital com alta eficiência de bateria e design moderno, elegante e fluido.",
    "pilot": "Mostrador híbrido com barras de progresso em arco pontilhado e visual de aviação.",
    "expressive": "Mostrador no estilo Material Expressive com inúmeras configurações e cores temáticas.",
    "auroraAnalog": "Mostrador analógico interativo com auroras boreais que reagem aos movimentos do pulso.",
    "nova": "Mostrador futurista e personalizável com infinitas combinações de temas.",
    "trackMate": "Mostrador esportivo e limpo que exibe seus dados essenciais em um instante.",
    "haze": "Leve, minimalista e descontraído. Aproveite os dias quentes de verão com estilo e elegância.",
    "peakShadow": "Inspirado na natureza. Um mostrador exclusivo, colorido e totalmente personalizável.",
    "apex2": "Segunda versão do aclamado design Apex, aprimorada com previsão do tempo horária e diária.",
    "tact5": "Mostrador tático moderno com 8 slots de complicações e temas exclusivos.",
    "explorer": "Mostrador analógico clássico com 8 complicações personalizáveis e belíssimos temas de cores.",
    "boost": "Mostrador focado em fitness com elegantes barras de cores e altíssima legibilidade.",
    "stealth": "Mostrador discreto e personalizável: temas escuros, complicações e fontes selecionáveis.",
    "military": "Fonte digital LCD exclusiva feita sob medida, com ricas opções de estilos e cores.",
    "roto": "Um mostrador dinâmico e inovador cujo layout gira suavemente a cada minuto.",
    "outdoor": "Mostrador vibrante, informativo e resistente para todas as suas aventuras ao ar livre.",
    "glide": "Relógio digital grande e nítido, complicações personalizadas e design contemporâneo.",
    "compact": "Mostrador fino e moderno com 8 complicações, fontes à sua escolha e temas variados.",
    "soft": "Mostrador minimalista com excelente legibilidade e os slots de complicações essenciais.",
    "ultra": "Mostrador moderno e versátil inspirado no visual analógico do Galaxy Watch Ultra.",
    "maverick": "O tempo redefinido. Maverick é o seu mostrador personalizável para os desafios do dia a dia.",
    "radial": "Relógio digital com fontes opcionais, cercado por 8 complicações circulares.",
    "kinetic": "Mostrador dinâmico e elegante com temas ricos, complicações e modo escuro AMOLED.",
    "aurora": "Mostrador minimalista com auroras boreais hipnotizantes que brilham ao mover o pulso.",
    "weatherAnalog": "Acompanhe o clima em tempo real e a previsão para as próximas 10 horas com visual limpo.",
    "forecast": "Previsão do tempo horária e diária, condições atuais, temperatura, índice UV e muito mais.",
    "summit": "Complicações sob medida, visual refinado, modos de horário e infinitas opções de estilo.",
    "pioneer": "Repleto de temas Material, fontes elegantes e 8 slots de complicações para máxima flexibilidade.",
    "pathfinder": "Mostrador analógico com temas de cores, estilos de ponteiros e complicações personalizáveis.",
    "halo": "Mostrador moderno e completo: combine livremente cores, fontes e complicações.",
    "spooky": "Atmosfera divertida de Halloween com diversos recursos práticos para o seu smartwatch.",
    "infoHub": "Sua central de informações pessoal no pulso com 6 complicações e temas atraentes.",
    "textTime": "Mostrador textual colorido e multilíngue que exibe o horário escrito por extenso.",
    "adventurer": "Mostrador rico e versátil inspirado no design Active do Pixel Watch 3.",
    "breezy": "Mostrador fresco e moderno: personalize facilmente cores, gradientes e complicações.",
    "symmetrical": "Crie um mostrador perfeitamente equilibrado graças aos seus slots simétricos.",
    "weather": "Clima ao vivo, previsão, probabilidade de chuva, índice UV e duas complicações dedicadas.",
    "mainGoals": "Design pensado para os seus objetivos diários com fontes opcionais e temas Material You.",
    "analogm4": "Mostrador Material You moderno com 8 complicações, estilos de ponteiros e acabamentos.",
    "binary2": "Mostrador sexagesimal em código binário. Toque na tela para revelar o relógio digital!",
    "apex": "Mostrador personalizável com fontes opcionais, gradientes coloridos e complicações úteis.",
    "inverted": "Veja o tempo ganhar vida enquanto o relógio digital se preenche a cada segundo que passa.",
    "classicm5": "Crie o seu mostrador clássico ideal escolhendo entre mais de 60 cores e temas diferentes.",
    "streamlined": "Animação suave do relógio digital, 6 complicações e dois modos de horário.",
    "perpetual": "Design digital de baixo consumo, desenvolvido com o Watch Face Format do Google.",
    "outlined": "Fontes com contorno personalizáveis, formato Watch Face Format e economia de energia.",
    "classicm3": "Inspirado no consagrado mostrador Clássico do Pixel Watch, otimizado e personalizável.",
    "nomad": "O estilo de vida nômade digital no seu pulso com um mostrador atraente, moderno e prático.",
    "timeMode": "4 modos de horário, 8 complicações personalizadas e excelente eficiência energética.",
    "timeFlow": "Design fluido e inovador sobre fundo preto puro, maximizando a vida útil da bateria.",
    "arcsd5": "Versão digital Arcs com fontes personalizáveis e 8 complicações completas.",
    "basicAnalog": "Mostrador analógico minimalista inspirado na tela de inicialização do Watch Face Format.",
    "arcsn6": "Mostrador analógico Watch Face Format com belíssimos arcos de progresso em gradiente.",
    "widgets2": "8 complicações, fontes de horário exclusivas e combinações de cores refinadas de alto nível.",
    "horizon9": "Mostrador digital OLED com display de 7 segmentos e 6 complicações organizadas.",
    "nord": "Projetado com Watch Face Format 2: personalização ilimitada e 8 complicações.",
    "gamerv1": "Para os apaixonados por games: fonte retrô arcade, monstros pixelados e visual exclusivo.",
    "manager": "Aumente sua produtividade com este mostrador profissional com excelente autonomia de bateria.",
    "active2": "Design focado em fitness com fundo preto puro e métricas esportivas dedicadas.",
    "dualtone": "Temas bicolores marcantes com efeito de brilho suave no relógio digital.",
    "infograph2": "Mostrador digital repleto de dados para todos os smartwatches com Wear OS 4+.",
    "infoblock2": "Barras de progresso em gradiente e 8 complicações completas num formato de baixo consumo.",
    "analogm3": "Mostrador analógico no estilo Material 3 com ponteiros e paletas de cores customizáveis.",
    "glancex": "Todas as suas informações essenciais num relance. Visual impecável no Pixel Watch.",
    "favoriteappstile": "Chega de rolar a lista de apps: abra seus favoritos direto a partir de um Bloco (Tile)!",
    "lucid": "Legibilidade cristalina, estilo Material Design e consumo de bateria reduzido ao mínimo.",
    "weathercomplications": "Complicações climáticas avançadas para Wear OS: UV, máxima/mínima, qualidade do ar e mais.",
    "chrono": "Mostrador híbrido com 7 complicações, múltiplos temas e excelente economia de bateria.",
    "react2": "Segunda edição do design React: visual moderno, alta responsividade e modularidade.",
    "modular": "Estrutura modular limpa com seleção de fontes e precisão perfeita pixel a pixel.",
    "sprint": "Mostrador esportivo criado no Watch Face Format, ágil e econômico na bateria.",
    "hugetime": "Horário digital em tamanho grande para leitura instantânea e 6 complicações úteis.",
    "controldash": "Painel de produtividade com 6 complicações sobre fundo preto puro OLED.",
    "angular": "Linhas geométricas marcantes, 7 complicações e fundo preto profundo que poupa bateria.",
    "pulse2": "Mostrador digital focado em saúde e fitness com quatro slots de dados em preto puro.",
    "rugged": "Robusto, imponente e durável, equipado com múltiplos slots para métricas e dados.",
    "pride": "Celebre a diversidade com as cores e símbolos do arco-íris LGBTQ+ no seu Wear OS.",
    "tactthree": "Mostrador tático para Wear OS 3 e 4 (API 30+), resistente e com ótimo rendimento de bateria.",
    "materialyou2": "Segunda edição Material You com duas barras de progresso e texturas em mesh.",
    "material4": "Mostrador digital em alta resolução com estética moderna e consumo mínimo de energia.",
    "pacifice": "Versão aprimorada do mostrador Pacific, compatível com todos os relógios Wear OS.",
    "engine": "Mostrador digital de alto padrão com inspiração mecânica de extrema precisão.",
    "concentric1": "Mostrador digital concêntrico, otimizado para telas OLED e com baixo consumo.",
    "nanox1": "Design híbrido colorido e diferenciado que une ponteiros tradicionais e horário digital.",
    "digitalinformer": "Mostrador informativo em estilo Material Design, personalizável e amigo da bateria.",
    "tempo": "Estilo dinâmico e atlético com complicações customizáveis e múltiplas opções de cores.",
    "alpine": "Mostrador híbrido com grande relógio digital e 8 complicações para a cidade e a montanha.",
    "photowatchface": "Exiba suas fotos prediletas no pulso a partir de modelos inclusos ou da sua galeria.",
    "photocomplication": "Complicação de fotos para Wear OS: defina qualquer imagem da sua galeria no mostrador.",
    "nitrous": "Design analógico esportivo com diversas complicações e perfil de baixo consumo.",
    "react": "Mostrador Wear OS econômico na bateria com diversos estilos de cores e complicações.",
    "guard": "Mostrador digital nítido e contemporâneo projetado para preservar a bateria.",
    "marine": "Inspiração náutica refinada, acabamento perfeito pixel a pixel e excelente autonomia.",
    "mnmlanalog": "A essência do minimalismo analógico: sóbrio, elegante e muito econômico na bateria.",
    "xface": "Monitore sua frequência cardíaca em tempo real com um layout claro e ágil.",
    "tacttwo": "Mostrador tático de alta precisão com consumo de energia reduzido ao mínimo.",
    "infoblock": "Inspirado na organização em blocos informativos, prático, claro e personalizável.",
    "circuit": "Inspirado em circuitos eletrônicos sobre preto puro com 7 complicações e 30 temas.",
    "progress": "Mostrador inovador onde o passar do tempo é representado por barras de progresso.",
    "analogpro": "Mostrador analógico profissional com design moderno, totalmente configurável.",
    "athlete2lite": "Versão leve do Athlete 2 com barras em gradiente e complicações essenciais.",
    "athlete2": "Dedicado ao desempenho esportivo no Wear OS 3+, otimizado e muito versátil.",
    "pulse": "Acompanhamento completo da sua saúde, barras em gradiente e preto puro OLED.",
    "pixeloled": "Estilo Material You inspirado no Pixel Watch com complicações personalizáveis.",
    "hyb": "Horas digitais em grande gradiente e barras de progresso para minutos e segundos.",
    "analogxt": "Mostrador analógico simples, limpo e direto para o seu relógio Wear OS.",
    "fitx": "Mostrador para saúde e condicionamento físico, personalizável e econômico na bateria.",
    "slimdigital": "Horário digital esguio e nítido sobre fundo preto puro OLED com complicações.",
    "simpleanalog": "Mostrador analógico sóbrio no estilo Material Design com fundo preto absoluto.",
    "widgets1": "8 complicações personalizáveis num mostrador Wear OS com grande autonomia de bateria.",
    "bigdigital": "Grandes números digitais de fácil leitura, app leve e excelente duração de bateria.",
    "weatherdigital": "Relógio digital de grande formato acompanhado por uma ampla complicação climática.",
    "materialyou": "Criado para Wear OS seguindo os princípios Material You: adaptável e econômico.",
    "healthface2": "Mostrador de saúde e bem-estar para smartwatches Wear OS com monitoramento contínuo.",
    "xviper": "Mostrador analógico moderno e arrojado com complicações e consumo controlado.",
    "pace3": "Mostrador para corrida com duas complicações graduadas de intervalo personalizáveis.",
    "gradient": "Animações suaves em gradiente, grande fonte digital e fundo preto puro.",
    "material3": "Design Material 3 com integração refinada de complicações e temas dinâmicos.",
    "tactq": "Visual tático militar com fundos camuflados intercambiáveis.",
    "retro": "Inspiração retrô digital dos anos 80 em um formato atualizado e amigo da bateria.",
    "edge": "Mostrador limpo e direto com as complicações fundamentais, ideal para telas OLED.",
    "sportive": "Mostrador premium que alia alta resolução gráfica, visual atlético e autonomia.",
    "simpledigital": "Exibição digital nítida e direta, desenvolvida para não sobrecarregar a bateria.",
    "catalyst": "Portado com sucesso do Tizen OS: acabamento de qualidade, nitidez e personalização.",
    "athlete1": "Mostrador focado em saúde para atletas e entusiastas de atividades físicas.",
    "hscomplications": "Complicações completas de saúde: distância, andares, calorias, passos e batimentos.",
    "weekdayutccomp": "Conjunto útil de complicações que exibem o dia da semana e o horário UTC.",
    "tactone": "Mostrador tático com horário digital, redutor de brilho e preto profundo.",
    "sportb": "Mostrador esportivo para Wear OS 3+ com grandes números em negrito e vários fundos.",
    "fusion": "Mostrador digital fitness com cores vibrantes em gradiente e ótima gestão de energia.",
    "esport": "Projetado para e-sports e atletas: números digitais grandes e leitura imediata.",
    "run4": "Série RUN: tipografia marcante de alto contraste pensada para seus treinos diários.",
    "frontier2": "Mostrador analógico com ponteiros robustos, estilo aventureiro e pretos profundos.",
    "leandigital": "Display digital LCD diferenciado com pegada esportiva e gráficos muito bem cuidados.",
    "talon": "Design híbrido sofisticado: alterne facilmente entre o mostrador analógico e o digital.",
    "glow": "Mostrador digital refinado com efeito de brilho suave e precisão pixel a pixel.",
    "ladiesclassic": "Mostrador clássico e gracioso equipado com 4 complicações personalizadas.",
    "awfoledanalog": "Mostrador analógico da OLED Studios, altamente personalizável e econômico.",
    "os3digital": "Mostrador para Wear OS 3+ com atalhos para apps, complicações e várias cores.",
    "hive": "Edição Pro digital sobre fundo preto puro com textura colmeia e cores intensas.",
    "binary": "Leitura binária do horário: ideal para programadores e entusiastas de tecnologia.",
    "fit3": "Mostrador digital exclusivo para treino: ágil, preciso e perfeitamente equilibrado.",
    "rushe": "Energia esportiva vibrante para relógios Wear OS com gráficos em alta definição.",
    "fitoled": "Edição especial OLED da linha Fit: 30 variações de cores e personalização completa.",
    "awffit5": "Mostrador fitness dinâmico para Wear OS, rico em cores e opções práticas.",
    "awfinformerx": "Mostrador Informer X sobre preto puro: clareza exemplar e dados em tempo real.",
    "awfpixelanalog": "Mostrador analógico preto absoluto com acabamento impecável pixel a pixel.",
    "awfmnmlthin": "Mostrador digital minimalista com tipografia fina e contemporânea.",
    "awftrueanalog": "Pera Analógica: mostrador elegante com um amplo leque de customizações.",
    "awfwave": "Elegante relógio digital com ponteiro de segundos ondulado sobre fundo preto OLED.",
    "awfdashboardA": "Painel fitness sobre fundo preto puro com padrão visual indiscutivelmente premium.",
    "awfuxanalog": "Mostrador analógico detalhado oferecendo ricas opções de personalização.",
    "awfpace2": "Mostrador digital voltado para esportes e corrida sobre fundo preto absoluto.",
    "awfmodernminimal": "Mostrador Pro minimalista que alia ponteiros clássicos a um fundo preto profundo.",
    "awfdigitalxr": "Mostrador digital Wear OS de alta qualidade com ampla variedade de estilos e cores.",
    "awffittwo": "Precisão milimétrica e acompanhamento constante de treino sobre preto puro.",
    "awffitone": "Mostrador digital que une esportividade e economia de bateria para o seu dia a dia.",
    "awfrun3": "Mostrador de corrida: digital, resistente e com alto contraste para leitura fácil ao ar livre.",
    "awflcddigital": "Display de cristal líquido retrô sobre fundo preto intenso para Wear OS.",
    "awfhikeone": "Criado para caminhadas e trilhas: números grandes com alta visibilidade sob o sol.",
    "awfsportydigital": "Mostrador fitness ágil e responsivo, perfeitamente otimizado para telas AMOLED.",
    "awftrondark": "Inspiração futurista no universo TRON sobre fundo preto absoluto para Wear OS.",
    "awftactical": "Inspiração militar e operacional com visual digital sólido, robusto e claro.",
    "awfactivexv": "Fontes de altíssima legibilidade para este mostrador digital que poupa bateria.",
    "awfinfograph": "Estilo infográfico que organiza harmoniosamente todas as suas métricas primordiais.",
    "awfsportxr": "Mostrador digital desenvolvido sob medida para acompanhar seu estilo de vida ativo.",
    "awfowly": "Um mostrador artístico e original com os olhos estilizados de uma coruja elegante.",
    "awfhealthface": "Mostrador digital centrado no acompanhamento da sua saúde e atividade corporal.",
    "awfterminal": "Inspirado no terminal de comando Linux para desenvolvedores, programadores e geeks.",
    "awfdashdigital": "Painel multicolorido sobre fundo preto OLED com resumo contínuo das suas atividades.",
    "awfdashanalog": "Mostrador analógico para fitness com indicadores curvos em gradiente de cores.",
    "awfparts": "Componentes digitais modulares sobre fundo preto profundo para Wear OS.",
    "awfcasual": "Mostrador versátil, sóbrio e confortável sobre preto puro, perfeito para o dia a dia.",
    "awfmotion0x": "Personalidade esportiva e moderna num mostrador analógico de alto contraste.",
    "awfmnmlglow": "Efeito sutil de brilho neon sobre preto absoluto para um visual noturno impecável.",
    "awfdashboard": "Mostrador voltado ao bem-estar diário, feito para acompanhar seu ritmo o dia todo.",
    "awfladiesanalog2": "Mostrador analógico feminino de alto nível, personalizável e econômico na bateria.",
    "awfminimal": "A elegância do minimalismo absoluto sobre preto puro com consumo de bateria reduzido.",
    "awfclassicface": "A sofisticação eterna da relojoaria analógica clássica em tela escura OLED.",
    "awftic": "Mostrador híbrido equilibrado com complicações sob medida e visual esportivo.",
    "awfcleandigital": "Exibição digital limpa, precisa e agradável sobre fundo preto absoluto.",
    "awfdigital1": "Números digitais grandes e bem visíveis para você ver as horas numa fração de segundo.",
    "awfanjuna": "Mostrador híbrido com nuances luminosas elegantes sobre fundo preto profundo.",
    "phonebattcomp": "Complicação Wear OS que exibe a porcentagem da bateria do seu smartphone no relógio.",
    "awfladiesrun": "Versão esportiva da série RUN desenvolvida especialmente para o público feminino.",
    "awfpolarevent": "Planeje seu dia com facilidade graças à complicação dedicada ao próximo evento da agenda.",
    "awfone": "Sobriedade, preto puro e gerenciamento exemplar da bateria no seu Wear OS.",
    "awflines": "Leitura inovadora do horário escrito em palavras com lindas combinações de cores.",
    "awfactiveanalog": "Mostrador analógico vibrante e econômico para acompanhar sua rotina diária.",
    "awflmoderna": "Mostrador analógico contemporâneo, charmoso e exclusivo para pulsos femininos.",
    "awfrun2": "Mostrador de corrida resistente e bem contrastado, feito para você superar seus limites.",
    "awfsportyanalog": "Mostrador analógico com alma esportiva, pretos intensos e longa autonomia de bateria.",
    "awfmohawk": "Mostrador digital original e marcante, feito para economizar bateria o dia inteiro.",
    "awfhealthd": "Monitore seus parâmetros corporais com este mostrador limpo sobre preto puro.",
    "awfpolaranalog": "Design analógico sóbrio e equilibrado garantindo excelente autonomia de bateria.",
    "awfpixelface": "Gráficos em pixel art minimalistas com consumo de energia rigorosamente controlado.",
    "awfrun": "O pioneiro da série RUN: máxima visibilidade, precisão e confiança a cada quilômetro.",
    "awfoutback": "Pronto para atividades ao ar livre com alto contraste e grande eficiência de bateria.",
    "awfpolar": "Suaves gradientes de cores sobre preto profundo neste mostrador digital elegante.",
    "awfdynamicpro": "Visualização digital dinâmica e versátil projetada para relógios Wear OS.",
    "awfmovehyb": "Combinação perfeita entre ponteiros clássicos e métricas digitais em fundo preto puro.",
    "awfpacepro": "Mostrador atlético de alta performance desenvolvido para poupar sua bateria.",
    "awfnewdigital2": "Relógio digital moderno, fundo preto profundo e excelente eficiência comprovada.",
    "awfaeonbpm": "Mostrador analógico com monitor de frequência cardíaca sobre fundo preto OLED.",
    "sportxdark": "Mostrador esportivo escuro de alto contraste, perfeitamente otimizado para Wear OS.",
    "awfnewdigital": "A simplicidade do digital com fundo preto puro e bateria que dura muito mais."
}
