"""
scripts/descriptions_it.py
Clean, idiomatic, professional Italian short descriptions for all 226 watch faces and apps.
"""

DESCRIPTIONS_IT = {
    "adventurer2": "Disponibile a breve...",
    "ultra2": "Quadrante elegante e altamente personalizzabile, ispirato allo stile analogico del Galaxy Watch Ultra 2.",
    "matte": "Quadrante semplice e raffinato con grande orologio digitale e complicazioni personalizzabili.",
    "military2": "Estetica tattica, font digitale LCD migliorato e ampie possibilità di personalizzazione.",
    "vertex": "Layout circolare con 8 complicazioni personalizzabili. Semplice, pulito ed efficace.",
    "zenith": "7 slot per complicazioni, meteo dettagliato, barre di avanzamento a gradiente e molto altro.",
    "gravity": "Progettato secondo lo stile nativo di Wear OS. Altamente personalizzabile e a basso consumo.",
    "epoch": "Quadrante analogico elegante con anelli della data dinamici e complicazioni personalizzabili.",
    "grid": "Solo complicazioni personalizzate, essenziale ed efficace.",
    "digest": "Due grandi slot per complicazioni per visualizzare il massimo delle informazioni a colpo d'occhio.",
    "expedition": "Un quadrante estremamente informativo dotato di 8 slot per complicazioni personalizzabili.",
    "utility": "Quadrante in stile Material Design altamente personalizzabile con 8 complicazioni su misura.",
    "rugged2": "Progettato per le condizioni estreme con orario in evidenza e complicazioni robuste.",
    "weatherDashboard": "Meteo attuale, previsioni complete, indice UV, probabilità di pioggia e complicazioni.",
    "pixelAnalog2": "Quadrante personalizzabile caratterizzato da un orologio analogico compatto ed elegante.",
    "wayfarer": "Design analogico a basso consumo e altamente personalizzabile. Rendilo unico con il tuo stile.",
    "vibe": "Quadrante compatto ed efficiente con disposizione radiale degli slot per complicazioni.",
    "circleDashboard": "Quadrante moderno e personalizzabile ispirato alla Circle Dashboard del Galaxy Watch.",
    "everyday": "Quadrante espressivo in stile Material 3, pulito, minimale e completamente personalizzabile.",
    "eccentric": "Quadrante moderno con font digitali distintivi e numerose opzioni di stile.",
    "adaptive": "Quadrante digitale ad alta efficienza energetica, dal design moderno, elegante e fluido.",
    "pilot": "Quadrante ibrido con barre di avanzamento ad arco tratteggiato ed estetica da aviatore.",
    "expressive": "Quadrante in stile Material Expressive con tantissime configurazioni e colori a tema.",
    "auroraAnalog": "Quadrante analogico con aurore boreali dinamiche che reagiscono al movimento del polso.",
    "nova": "Quadrante futuristico e altamente personalizzabile con infinite combinazioni di temi.",
    "trackMate": "Quadrante sportivo e pulito che mostra i tuoi dati essenziali in un istante.",
    "haze": "Leggero, minimale e rilassato. Vivi le calde giornate estive con stile ed eleganza.",
    "peakShadow": "Ispirato alla natura. Un quadrante unico, vivace e completamente personalizzabile.",
    "apex2": "Seconda versione del celebre design Apex, arricchita con previsioni meteo orarie e giornaliere.",
    "tact5": "Quadrante tattico moderno con 8 slot per complicazioni e combinazioni di colori uniche.",
    "explorer": "Quadrante analogico classico con 8 complicazioni personalizzabili e splendidi temi di colore.",
    "boost": "Quadrante orientato al fitness con suggestive barre colorate e massima leggibilità.",
    "stealth": "Quadrante stealth personalizzabile: temi scuri, complicazioni, font orario e molto altro.",
    "military": "Font digitale LCD esclusivo progettato su misura, con ricche opzioni di stile e tonalità.",
    "roto": "Un quadrante originale e dinamico il cui layout ruota armoniosamente ogni minuto.",
    "outdoor": "Quadrante vivace, informativo e resistente per tutte le tue avventure all'aperto.",
    "glide": "Grande orologio digitale ben visibile, complicazioni personalizzate e design contemporaneo.",
    "compact": "Quadrante sottile e moderno con 8 complicazioni, font a scelta e molteplici temi.",
    "soft": "Quadrante minimale e ad altissima leggibilità con gli slot di complicazione essenziali.",
    "ultra": "Quadrante moderno e flessibile ispirato all'estetica del Galaxy Watch Ultra Analog.",
    "maverick": "Il tempo ridefinito. Maverick è il tuo quadrante personalizzabile per le sfide di ogni giorno.",
    "radial": "Orologio digitale con font opzionali, circondato da 8 complicazioni ad anello.",
    "kinetic": "Quadrante dinamico ed elegante con temi ricchi, complicazioni e modalità scura AMOLED.",
    "aurora": "Quadrante minimale con splendide aurore boreali che brillano al movimento del polso.",
    "weatherAnalog": "Monitora il meteo attuale e le previsioni a 10 ore in un design analogico minimale.",
    "forecast": "Previsioni meteo orarie e giornaliere, condizioni attuali, temperatura, indice UV e altro.",
    "summit": "Complicazioni su misura, linee pulite, modalità orarie e infinite opzioni di stile.",
    "pioneer": "Ricco di temi Material, font ricercati e 8 slot per complicazioni per la massima flessibilità.",
    "pathfinder": "Quadrante analogico con temi colore, stili di lancette e complicazioni personalizzabili.",
    "halo": "Quadrante moderno e completo: combina liberamente colori, caratteri e complicazioni.",
    "spooky": "Atmosfera di Halloween divertente e ricca di funzioni utili per il tuo smartwatch.",
    "infoHub": "Il tuo centro informazioni personale al polso con 6 complicazioni e temi accattivanti.",
    "textTime": "Quadrante testuale multilingue e colorato per leggere l'orario scritto in parole.",
    "adventurer": "Quadrante ricco e versatile ispirato al design Active del Pixel Watch 3.",
    "breezy": "Quadrante fresco e moderno: personalizza con facilità colori, gradienti e complicazioni.",
    "symmetrical": "Componi un quadrante perfettamente bilanciato grazie agli slot simmetrici.",
    "weather": "Meteo in tempo reale, previsioni, probabilità di pioggia, indice UV e due complicazioni.",
    "mainGoals": "Design pensato per i tuoi obiettivi quotidiani con font a scelta e temi Material You.",
    "analogm4": "Quadrante Material You personalizzabile con 8 complicazioni e stili di lancette unici.",
    "binary2": "Quadrante sessagesimale codificato in binario. Tocca lo schermo per mostrare l'ora digitale!",
    "apex": "Quadrante personalizzabile con font selezionabili, sfumature di colore e complicazioni.",
    "inverted": "Guarda il tempo prendere vita mentre l'orologio digitale si riempie secondo dopo secondo.",
    "classicm5": "Crea il tuo quadrante classico perfetto scegliendo tra oltre 60 colori e temi diversi.",
    "streamlined": "Animazione fluida dell'orologio digitale, 6 complicazioni e due modalità orarie.",
    "perpetual": "Design digitale a basso consumo energetico, realizzato con il Watch Face Format di Google.",
    "outlined": "Caratteri con contorno personalizzabili, formato Watch Face Format e consumo minimo.",
    "classicm3": "Ispirato al celebre quadrante Classico del Pixel Watch, ottimizzato e personalizzabile.",
    "nomad": "Lo stile di vita del nomade digitale al tuo polso con un quadrante accattivante e moderno.",
    "timeMode": "4 modalità orarie, 8 complicazioni personalizzate ed elevata efficienza energetica.",
    "timeFlow": "Design innovativo e fluido su sfondo nero puro, pensato per massimizzare la batteria.",
    "arcsd5": "Versione digitale Arcs con caratteri orari personalizzabili e 8 complicazioni complete.",
    "basicAnalog": "Quadrante analogico essenziale ispirato all'animazione di avvio del Watch Face Format.",
    "arcsn6": "Quadrante analogico Watch Face Format con splendidi archi di progressione a gradiente.",
    "widgets2": "8 complicazioni, font orari dedicati e raffinate combinazioni cromatiche di alto livello.",
    "horizon9": "Quadrante digitale OLED con display a 7 segmenti e 6 complicazioni ben organizzate.",
    "nord": "Progettato con Watch Face Format 2: massima personalizzazione e 8 complicazioni.",
    "gamerv1": "Dedicato agli appassionati di videogiochi: font arcade, personaggi pixel e look unico.",
    "manager": "Aumenta la tua produttività con questo quadrante professionale a basso consumo di batteria.",
    "active2": "Design orientato allo sport e al fitness con sfondo nero puro e metriche dedicate.",
    "dualtone": "Suggestivi temi bicolore con effetto bagliore digitale sull'orologio.",
    "infograph2": "Quadrante digitale ricco di informazioni per tutti gli smartwatch con Wear OS 4+.",
    "infoblock2": "Barre di avanzamento a sfumatura e 8 complicazioni in un design a bassissimo consumo.",
    "analogm3": "Quadrante analogico in stile Material 3 con lancette e palette colori personalizzabili.",
    "glancex": "Tutte le tue informazioni chiave a colpo d'occhio. Resa impeccabile su Pixel Watch.",
    "favoriteappstile": "Basta scorrere l'elenco delle app: avvia le tue preferite direttamente da un Riquadro!",
    "lucid": "Leggibilità cristallina, stile Material Design e consumo di batteria ridotto al minimo.",
    "weathercomplications": "Complicazioni meteo avanzate per Wear OS: UV, temperature min/max, qualità dell'aria e altro.",
    "chrono": "Quadrante ibrido con 7 complicazioni, molteplici temi cromatici e consumi ridotti.",
    "react2": "Seconda edizione del design React: look contemporaneo, reattività e versatilità.",
    "modular": "Struttura modulare pulita con font selezionabili e precisione perfetta al pixel.",
    "sprint": "Quadrante sportivo realizzato con Watch Face Format, rapido e a basso consumo.",
    "hugetime": "Orario digitale a grandi cifre per una lettura immediata e 6 utili complicazioni.",
    "controldash": "Dashboard per la produttività con 6 complicazioni su sfondo nero puro OLED.",
    "angular": "Linee geometriche decise, 7 complicazioni e sfondo nero profondo salva-batteria.",
    "pulse2": "Quadrante digitale per salute e fitness con quattro slot di dati su sfondo nero puro.",
    "rugged": "Robusto, massiccio e resistente, dotato di molteplici slot per dati e complicazioni.",
    "pride": "Celebra l'inclusione con i colori e i simboli dell'arcobaleno LGBTQ+ su Wear OS.",
    "tactthree": "Quadrante tattico per Wear OS 3 e 4 (API 30+), solido e a risparmio energetico.",
    "materialyou2": "Seconda edizione Material You con due barre di avanzamento e sfondi con texture mesh.",
    "material4": "Quadrante digitale ad alta risoluzione con grafica moderna e consumi minimi.",
    "pacifice": "Versione perfezionata del quadrante Pacific, compatibile con ogni dispositivo Wear OS.",
    "engine": "Quadrante digitale di alta gamma con un'estetica meccanica di precisione.",
    "concentric1": "Quadrante digitale concentrico, ottimizzato per schermi OLED a basso consumo.",
    "nanox1": "Design ibrido vivace e distintivo che unisce orologio analogico e orario digitale.",
    "digitalinformer": "Quadrante in stile Material Design, ricco di informazioni e gentile con la batteria.",
    "tempo": "Quadrante sportivo e dinamico con complicazioni personalizzate e molteplici stili.",
    "alpine": "Quadrante ibrido con grande orologio digitale e 8 complicazioni per la città e la natura.",
    "photowatchface": "Mostra le tue foto preferite al polso da una selezione inclusa o dalla tua galleria.",
    "photocomplication": "Complicazione fotografica per Wear OS: imposta qualsiasi immagine della tua galleria.",
    "nitrous": "Design analogico sportivo con numerose complicazioni e profilo a basso consumo.",
    "react": "Quadrante Wear OS a basso consumo con tantissimi stili di colore e complicazioni.",
    "guard": "Quadrante digitale nitido e moderno progettato per preservare la batteria.",
    "marine": "Ispirazione nautica di pregio, cura meticolosa di ogni pixel e ottima autonomia.",
    "mnmlanalog": "La purezza del minimalismo analogico: sobrio, elegante e salva-batteria.",
    "xface": "Monitora il tuo battito cardiaco in tempo reale con un layout chiaro e reattivo.",
    "tacttwo": "Quadrante tattico ad alta precisione con consumo energetico ridotto al minimo.",
    "infoblock": "Ispirato al layout a blocchi informativi, pratico, chiaro e personalizzabile.",
    "circuit": "Ispirazione circuiti elettronici su nero puro con 7 complicazioni e 30 temi cromatici.",
    "progress": "Quadrante d'avanguardia in cui lo scorrere del tempo è mostrato da barre di progresso.",
    "analogpro": "Quadrante analogico professionale dal design moderno, completamente configurabile.",
    "athlete2lite": "Versione leggera di Athlete 2 con barre a sfumatura e complicazioni essenziali.",
    "athlete2": "Dedicato alle prestazioni e allo sport su Wear OS 3+, ottimizzato e versatile.",
    "pulse": "Monitoraggio completo dei tuoi parametri, barre a gradiente e nero puro OLED.",
    "pixeloled": "Stile Material You ispirato al Pixel Watch con complicazioni personalizzabili.",
    "hyb": "Ore digitali a grande sfumatura e barre di avanzamento per minuti e secondi.",
    "analogxt": "Quadrante analogico semplice, essenziale e chiaro per Wear OS.",
    "fitx": "Quadrante per salute e fitness, personalizzabile e a basso consumo di batteria.",
    "slimdigital": "Orario digitale compatto e nitido su sfondo nero puro OLED con complicazioni.",
    "simpleanalog": "Quadrante analogico sobrio in stile Material Design con sfondo nero assoluto.",
    "widgets1": "8 complicazioni personalizzabili in un quadrante Wear OS ad alta autonomia.",
    "bigdigital": "Grandi cifre digitali facili da leggere, app leggera ed eccellente durata della batteria.",
    "weatherdigital": "Orologio digitale di grandi dimensioni affiancato da un'ampia complicazione meteo.",
    "materialyou": "Creato per Wear OS seguendo i canoni Material You: adattivo e a basso consumo.",
    "healthface2": "Quadrante salute e benessere per smartwatch Wear OS con monitoraggio costante.",
    "xviper": "Quadrante analogico moderno e grintoso con complicazioni e consumi contenuti.",
    "pace3": "Quadrante fitness con due complicazioni graduate ad intervallo personalizzabili.",
    "gradient": "Animazioni con sfumature fluide, grande font digitale e sfondo nero puro.",
    "material3": "Design Material 3 con integrazione avanzata delle complicazioni e temi dinamici.",
    "tactq": "Stile militare tattico con sfondi mimetici intercambiabili.",
    "retro": "Ispirazione digitale rétro anni '80 in un formato contemporaneo e salva-batteria.",
    "edge": "Quadrante pulito ed essenziale con le complicazioni chiave, perfetto per display OLED.",
    "sportive": "Quadrante premium che unisce grafica ad alta risoluzione, look atletico e autonomia.",
    "simpledigital": "Visualizzazione digitale chiara e diretta, studiata per non gravare sulla batteria.",
    "catalyst": "Portato con successo da Tizen OS: finiture di qualità, grafica nitida e personalizzazione.",
    "athlete1": "Quadrante orientato alla salute per atleti e appassionati di attività fisica.",
    "hscomplications": "Complicazioni avanzate per il benessere: distanza, piani, calorie, passi e battito.",
    "weekdayutccomp": "Complicazioni personalizzate utili che mostrano il giorno della settimana e l'ora UTC.",
    "tactone": "Quadrante tattico con orario digitale, attenuatore di luminosità e nero profondo.",
    "sportb": "Quadrante sportivo per Wear OS 3+ con grandi numeri in grassetto e vari sfondi.",
    "fusion": "Quadrante fitness digitale con vivaci sfumature di colore e gestione energetica ideale.",
    "esport": "Ideato per e-sport e atleti: grandi cifre digitali e leggibilità immediata.",
    "run4": "Serie RUN: grafica audace ad alto contrasto concepita per le tue sessioni di allenamento.",
    "frontier2": "Quadrante analogico con lancette robuste, aspetto d'avventura e neri profondi.",
    "leandigital": "Display digitale LCD distintivo con taglio sportivo e grafica curata nei dettagli.",
    "talon": "Design ibrido prestigioso: passa agevolmente dalla visualizzazione analogica a quella digitale.",
    "glow": "Quadrante digitale ricercato con elegante effetto bagliore e precisione al pixel.",
    "ladiesclassic": "Quadrante classico ed elegante arricchito da 4 complicazioni su misura.",
    "awfoledanalog": "Quadrante analogico firmato OLED Studios, versatile e ad alta efficienza energetica.",
    "os3digital": "Quadrante per Wear OS 3+ con scorciatoie app, complicazioni e molteplici colorazioni.",
    "hive": "Edizione Pro digitale su sfondo nero puro con motivo ad alveare e colori intensi.",
    "binary": "Lettura binaria dell'orario: ideale per programmatori, informatici e appassionati di tecnologia.",
    "fit3": "Quadrante digitale unico per l'allenamento: snello, preciso e perfettamente calibrato.",
    "rushe": "Spirito sportivo e grintoso per Wear OS con grafica ad altissima definizione.",
    "fitoled": "Edizione speciale OLED della linea Fit: 30 colorazioni e personalizzazione completa.",
    "awffit5": "Quadrante fitness dinamico per Wear OS, ricco di colore e opzioni pratiche.",
    "awfinformerx": "Quadrante Informer X su nero puro: chiarezza esemplare e dati in tempo reale.",
    "awfpixelanalog": "Quadrante analogico nero assoluto con grafica impeccabile rifinita al pixel.",
    "awfmnmlthin": "Quadrante digitale minimale con tipografia sottile e contemporanea.",
    "awftrueanalog": "Pera Analogica: quadrante raffinato con un ventaglio completo di personalizzazioni.",
    "awfwave": "Elegante orologio digitale con originale lancetta dei secondi a onda su sfondo nero OLED.",
    "awfdashboardA": "Dashboard fitness su sfondo nero puro con finiture di indiscutibile pregio.",
    "awfuxanalog": "Quadrante analogico curato nei minimi dettagli con ricche opzioni di personalizzazione.",
    "awfpace2": "Quadrante digitale orientato all'attività sportiva e alla corsa su sfondo nero puro.",
    "awfmodernminimal": "Quadrante Pro minimale che unisce lancette tradizionali a uno sfondo nero profondo.",
    "awfdigitalxr": "Quadrante digitale Wear OS di alta qualità con una vasta gamma di stili e colori.",
    "awffittwo": "Precisione al millimetro e monitoraggio costante dell'allenamento su nero profondo.",
    "awffitone": "Quadrante digitale che fonde sportività e risparmio energetico per le tue giornate.",
    "awfrun3": "Quadrante per la corsa: digitale, resistente e ad alto contrasto per una lettura agevole.",
    "awflcddigital": "Display a cristalli liquidi rétro su sfondo nero intenso per Wear OS.",
    "awfhikeone": "Ideato per le escursioni: grandi cifre ad alta visibilità anche sotto la luce del sole.",
    "awfsportydigital": "Quadrante fitness scattante e reattivo, ottimizzato al meglio per display AMOLED.",
    "awftrondark": "Ispirazione fantascientifica e universo TRON su sfondo nero assoluto per Wear OS.",
    "awftactical": "Ispirazione militare e operativa con lettura dell'orario digitale solida e chiara.",
    "awfactivexv": "Caratteri ad altissima leggibilità per questo quadrante digitale parco nei consumi.",
    "awfinfograph": "Stile infografico che raggruppa in modo armonioso tutte le tue metriche primarie.",
    "awfsportxr": "Quadrante digitale pensato appositamente per chi ama uno stile di vita attivo.",
    "awfowly": "Un quadrante artistico e originale con il volto stilizzato di un simpatico gufo.",
    "awfhealthface": "Quadrante digitale incentrato sul monitoraggio della tua salute e del movimento.",
    "awfterminal": "Ispirato al terminale a riga di comando per sviluppatori, programmatori e geek.",
    "awfdashdigital": "Dashboard multicolore su sfondo nero OLED con riepilogo continuo dell'attività.",
    "awfdashanalog": "Quadrante analogico per il fitness con indicatori curvi a sfumatura di colore.",
    "awfparts": "Componenti digitali modulari su sfondo nero profondo per Wear OS.",
    "awfcasual": "Quadrante versatile, sobrio e comodo su sfondo nero puro per l'uso quotidiano.",
    "awfmotion0x": "Carattere sportivo e moderno in un quadrante analogico ad elevato contrasto.",
    "awfmnmlglow": "Sottile effetto bagliore su nero assoluto per un look notturno sofisticato.",
    "awfdashboard": "Quadrante orientato al benessere quotidiano, pensato per accompagnarti tutto il giorno.",
    "awfladiesanalog2": "Quadrante analogico femminile di fascia alta, personalizzabile e a basso consumo.",
    "awfminimal": "L'eleganza del minimalismo essenziale su nero puro con consumi di batteria ridotti.",
    "awfclassicface": "L'intramontabile classe dell'orologeria analogica su sfondo scuro OLED.",
    "awftic": "Quadrante ibrido bilanciato con complicazioni su misura e aspetto sportivo.",
    "awfcleandigital": "Visualizzazione digitale nitida, precisa e pulita su sfondo nero assoluto.",
    "awfdigital1": "Cifre digitali grandi e ben visibili per leggere l'orario in una frazione di secondo.",
    "awfanjuna": "Quadrante ibrido dalle raffinate sfumature luminose su sfondo nero profondo.",
    "phonebattcomp": "Complicazione Wear OS che mostra il livello di batteria del tuo smartphone (%).",
    "awfladiesrun": "Variante sportiva della serie RUN creata su misura per i polsi femminili.",
    "awfpolarevent": "Pianifica al meglio la tua giornata con la complicazione dedicata al prossimo evento.",
    "awfone": "Sobrietà, nero puro e gestione impeccabile della batteria su Wear OS.",
    "awflines": "Lettura originale dell'orario in lettere arricchita da splendide tonalità cromatiche.",
    "awfactiveanalog": "Quadrante analogico dinamico e parsimonioso nei consumi per le attività quotidiane.",
    "awflmoderna": "Quadrante analogico contemporaneo, raffinato ed esclusivo per il pubblico femminile.",
    "awfrun2": "Quadrante per la corsa resistente e ben contrastato, concepito per dare il massimo.",
    "awfsportyanalog": "Quadrante analogico dall'anima sportiva con neri intensi e lunga autonomia.",
    "awfmohawk": "Quadrante digitale originale e grintoso, concepito per preservare la carica.",
    "awfhealthd": "Tieni sotto controllo i parametri di salute con questo quadrante pulito su nero puro.",
    "awfpolaranalog": "Design analogico sobrio ed essenziale per garantire la massima durata della batteria.",
    "awfpixelface": "Grafica pixel art minimale con una gestione impeccabile dei consumi energetici.",
    "awfrun": "Il capostipite della serie RUN: leggibilità al vertice e affidabilità continua.",
    "awfoutback": "Pronto per l'avventura all'aperto grazie all'elevato contrasto e all'alta efficienza.",
    "awfpolar": "Delicate sfumature di colore su nero profondo per questo quadrante digitale fluido.",
    "awfdynamicpro": "Visualizzazione digitale dinamica e versatile studiata per gli smartwatch Wear OS.",
    "awfmovehyb": "Connubio perfetto tra lancette tradizionali e dati digitali su sfondo nero puro.",
    "awfpacepro": "Quadrante atletico ad alte prestazioni progettato per salvaguardare la batteria.",
    "awfnewdigital2": "Orologio digitale moderno, sfondo nero profondo ed elevata efficienza provata.",
    "awfaeonbpm": "Quadrante analogico con cardiofrequenzimetro integrato su sfondo nero OLED.",
    "sportxdark": "Quadrante sportivo scuro e a forte contrasto, ottimizzato al meglio per Wear OS.",
    "awfnewdigital": "L'essenza del digitale con sfondo nero puro e autonomia prolungata al polso."
}
